wordpress-mobile/gutenberg-mobile

- App.js
- App.test.js
- block-management/block-holder.js
- jest.android.json
- package.json
- yarn.lock
Note: remember to `git submodule update` to fetch the proper GB branch.
Loads the ported `Code` block from Gutenberg.
* No proper styling ported
* Input box accepts text modifications but are overridden immediately. For the time being text changes only get logged to the console. 
* Test (`'Code block is a TextInput'`) that tests the input component's type (`TextInput` atm)
* The test (`'Code block is a TextInput'`) access the child components using hardcoded array indices 😭
> Load code block

- .babelrc
- .flowconfig
- block-management/block-holder.js
- block-management/block-manager.js
- package.json
- wordpress/hooks.js
- yarn.lock
Uses GB code to register and retrieve the `Code` block.
Note: Needs updating the submodule
Note 2: currently tests give out console error (`Block "core/code" is already registered.`) because the registration happens twice (2 tests in `App.test.js`). We need to figure out a better way to handle the registration lifecycle.
> Register and load Code block

- .babelrc
The GB has been updated to use single `.native.js` files for platform specific code instead of the dual `.android.js`+`.ios.js`.
> Use the .native.js file extension

- .babelrc
- package.json
- yarn.lock
When imported directly in GB code, GB's eslint errors out because it
finds React as an unused import. So, leaving it out and auto-importing
it in the RN project.
To test:
* Make sure you've run `git submodule update` to get the latest of the GB branch
* run `npm run lint` inside the `gutenberg` subdir and notice no error occurs
> Auto import React, don't import it in GB code

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
This PR updates the .gitignore file with the [latest GitHub settings for vscode](https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore).
It also adds the default settings for vscode, and the recommended extensions.
Before starting, make sure you uninstall the "Flow Language Support" and "JavaScript Atom Grammar" extensions from VS Code.
1. Make a fresh clone of this repository.
2. Launch VisualStudioCode.app and open the fresh clone of `mobile-gutenberg`.
3. Make sure you see the following recommendation in the bottom-left corner:
4. Tap on "Show Recommendations" and make sure you see this addon
5. Press `CMD ,`.  Select the "Workspace Settings" tab and make sure you see `"javascript.validate.enable": false`
> Updates gitignore. Adds vscode settings.

- package.json
- yarn.lock
New commands:
* `yarn clean`: delete watchmen, delete `node_modules`, delete lock file and clean up the metro cache.
* `yarn clean-install`: run `yarn clean` + `yarn install` (pretty common).
After running `yarn clean-install`, You won't need to add the `--reset-cache` option to `yarn start`, the metro cache will also be cleaned up which is handy in most case.
Note: this is very useful when switching between branches.
> New yarn clean and yarn clean-reset commands

- package.json
This PR adds a extra step to the clean build option to clear the yarn cache.
This helps on cases where the folder of caches is corrupted by any reason.
Question:  I notice that one of the clean steps is `yarn test --clear cache` has a step? Do we need to test to clear the cache of the test results?
> Add step to clear yarn cache of packages.

- README.md
It's been some time now that our processes and project structure has moved beyond the original Expo based setup so, it's high time to update the README.md.
Main changes:
* The app is now "ejected", no longer using Expo
* Using `yarn`
* Mention of some additional helper scripts (`test:debug`, `start:reset`, `clean:install`)
> Update README.md to reflect current project setup

- package.json
- rn-cli.config.js
- yarn.lock
With #66, the `@wordpress/data` package is pulled from NPM while the `@wordpress/element` from local GB source. Thing is, `data` tries to pull in the `element` package as well and that gets resolved from NPM. Apparently this ends up messing up with the locally loaded `element` package too. So, even though the `data` package doesn't contain any mobile native code (and thus we could just pull it from NPM) we seem forced to load it from local too.
This PR let's `@wordpress/data` be resolved from the local GB source tree.
1. Delete the local `node_modules` folder
2. Install the packages: `yarn install`
3. Clean-Start the bundler: `yarn start:reset`
4. In a separate terminal window build/install the app: `yarn android` or `yarn ios`
5. Notice the app launching normally
> Load the data package from local GB source tree

- package.json
This PR is a tiny change that will prevent yarn.lock from being deleted when doing `yarn clean` or modified when doing `yarn install`.
This is actually a positive change for development, to avoid having all PRs updating `yarn.lock` continuously, which could introduce seemingly-random and actually-unrelated issues.
It will allow us to separate updates to that file into a task of its own.
Running `yarn install` will still make sure you have the required dependencies for the branch you're in, so this should not affect our ability to stay up to date when changing branches.
- Do `yarn clean` and make sure the `yarn.lock` isn't deleted.
- Do `yarn install` and make sure the `yarn.lock` isn't modified.
- Run the app and make sure there are no outstanding errors.
> Stops deleting yarn.lock on clean.

- package.json
- yarn.lock
As reported [here](https://github.com/WordPress/gutenberg/issues/7936) some WordPress packages were missing a declaration of this dependency, forcing us [to explicitly require it ourselves](#72).
This PR resolves #71.
- Check out the branch.
- Do `yarn clean:install`.
- Do `grep "babel/runtime" yarn.lock` and make sure you get something like this:
```
"@babel/runtime@^7.0.0-beta.52":
resolved "https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.0.0-beta.54.tgz#39ebb42723fe7ca4b3e1b00e967e80138d47cadf"
"@babel/runtime" "^7.0.0-beta.52"
"@babel/runtime" "^7.0.0-beta.52"
"@babel/runtime" "^7.0.0-beta.52"
"@babel/runtime" "^7.0.0-beta.52"
"@babel/runtime" "^7.0.0-beta.52"
```
- Make sure the app runs as usual.
> Removes the babel/runtime explicit dependency.

- .babelrc
- .flowconfig
- jest.config.js
- package.json
- rn-cli.config.js
- src/block-management/block-holder.js
- src/block-management/block-manager.js
- src/globals.js
- src/parser/block-parser-code.test.js
- src/parser/block-parser-more.test.js
- src/store/index.js
- yarn.lock
Update to the currently latest Gutenberg master branch.
Changes:
* Using the @wordpress/blocks packages now, and directly from src
* For some reason, Flow doesn't like pointing to the root of the blocks
package (while it's not complaining for the same reason for the
`element` package). Having the flow config pointing inside the `src` dir
of the package now.
* Need to expose `window.Node` for a couple of its constants. Using
jsdom's definitions for that.
* Code block needs a css class defined (wp-block-code) in the innerHTML
for validation to succeed
> Update to latest GB master

- src/block-management/block-holder.js
This PR wraps up the initial wiring of Aztec to `gutenberg-mobile`.  It wires Aztec's content to our JavaScript state.
Closes #73.
This PR also introduces some changes to how we store `eventCount` in our JS code.
According to https://facebook.github.io/react-native/docs/state:
```text
There are two types of data that control a component: props and state. props
are set by the parent and they are fixed throughout the lifetime of a
component. For data that is going to change, we have to use state.
```
Since `eventCount` was being changed throughout the lifetime of the Aztec TextView component, moving it to `state` made the most sense to adhere to the documentation cited above.
Storing it as a `prop` (that's what I understand we were doing before) was causing issues on iOS's side of the code. …
> iOS: Aztec fully wired (v1).

- package.json
As we go back and forth from testing the[ `AztecRN wrapper`](https://github.com/wordpress-mobile/react-native-aztec) and gutenberg-mobile, it's been tedious to know and make sure things are clean and can be run seamlessly.
Adding a step here to clean RN installed in `/example` and `./` folders of `react-native-aztec` subtree, and updating the subtree commit to latest master in `react-native-aztec`.
**Test steps:**
Run Aztec demo app first so RN gets installed locally there, and then run Gutenberg.
1. ```cd gutenberg-mobile/react-native-aztec/example```
2. ```yarn clean:install```
3. ```yarn start --reset-cache```
4. on another window: ```yarn android``` or ```yarn iOS```
Once you confirm the Aztec demo app works alright, proceed to try running the Gutenberg mobile demo app:
1. ```cd …
```
> Add cleanup code for submodule react-native-aztec

- src/block-management/block-holder.js
This brings the implementation closer to the web by only changing the specified attributes instead of replacing everything with the passed attributes.
This means that callers don't need to be aware and prepend `...this.props.attributes` and can just worry about specifying the change they want, for instance:
```js
setAttributes( { dropCap: ! attributes.dropCap } );
```
This was added so that our `onChange` and `onContentSizeChange` methods don't need to have access to `this.props`, but also to match how the web behaves.
> Preserve existing attributes in setAttributes

- src/block-management/block-manager.js
This is a small PR that makes the text view that shows the HTML code editable.
There are a couple of "known issues" on **Android** that I'd prefer to fix later on, to not make this PR too big:
- The TextInput view appears scrolled to the bottom.
- Anywhere I tap to start typing, the cursor will appear at the bottom.
**Note**: Any change made will be lost when returning to the blocks view.
> Editable html view

- package.json
Reinstates the `clean:runtime` script that runs all the cleaning procedures needed after package installations and before Metro starts. This also fixes the broken `start:reset` script.
So, ideally, if the dependencies list hasn't changed (no new deps or upgraded deps or removed deps) than one just needs to `yarn start:reset` to clean-start Metro.
To test:
1. Run `yarn start:reset` to clean-start Metro and notice that it start correctly
> Reinstate clean:runtime script so start:reset works

- .eslintignore
- .flowconfig
- __mocks__/nodejsMock.js
- __mocks__/styleMock.js
- index.js
- jest.config.js
- package.json
- src/app/App.js
- src/app/AppContainer.js
- src/app/MainApp.js
- src/block-management/block-holder.js
- src/block-management/toolbar.js
- src/globals.js
- src/store/actions/index.js
- src/store/index.js
- src/store/reducers/index.js
- yarn.lock
The params passed to eslint command line specifying which source files to check were missing the subdirectories inside the `src` directory. See [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/88#discussion_r209577525) for example. This PR replaces the glob definition with the all-catching `.`.
The submodules are left out of the list though (see `.eslintignore` file) since those are checked in their respective repositories.
Also in this PR:
* Fix for the `yarn prettier` command to use `prettier-eslint-cli`
* Apply the `@flow` pragma to more source files so Flow should check those too
To test:
* compile and run the app; everything should run just fine
* run the linter (`yarn lint`) and tests (`yarn test`); all should run fine as well
* run the Flow checker (`yarn …
> Fix eslint missing src subdirs

- src/block-management/block-manager.js
This fixes the problem with keeping up with `focused` state as described in https://github.com/wordpress-mobile/gutenberg-mobile/pull/88#issuecomment-411477900.
Fixed by @hypest, copying here the description of what this does:
> I think that happens there is that onChange breaks the “contract” where the block instances in the DataSource need to be the very same ones as in the props
This diff effectively makes sure to use the same block instance and update the instance `attributes`, then sending the updated changes to the redux store.
props to @hypest once more.
> Inserter - fix focus handling, awesomely spotted by @hypest

- src/block-management/block-manager.js
After the change introduced in https://github.com/wordpress-mobile/gutenberg-mobile/pull/108, the first time the RecyclerView renders its items these will all have the same height, rendering some of the blocks "cut".
**BEFORE**
**AFTER**
This PR addresses this by making sure to set these items dirty, [signaling the RecyclerView to re-draw them](https://github.com/wordpress-mobile/react-native-recyclerview-list/blob/master/src/RecyclerViewList.js#L106) as `onChange` is received.
> Inserter - have the RecyclerView update and re-draw item in onChange

- src/app/AppContainer.js
- src/block-management/block-manager.js
- src/store/actions/index.js
- src/store/actions/test.js
- src/store/reducers/index.js
_Closing #96 in favor of this one, as the base branch of #95 is not needed anymore, and avoid messing with commit history_
Adds direct insertion at a specific index in the list state. For the sake of the exercise in the GB mobile application for now we're inserting right below the tapped block.
Before, it would only _append_ new blocks to the list.
> Inserter - added direct insertion to block manager (take2)

- src/block-management/block-manager.js
- src/store/reducers/index.js
This PR performs a `dataSource` re-init (by recreating the object in the `state`) when a full `parse` has taken place. While we've avoided re-creating the list's `dataSource` in other cases, I think it makes sense to do so after an html-to-blocks conversion has taken place. 
This makes sure the state of `dataSource`, and `props` are aligned, and fixes the detail described in #100 here:
> On Android, this currently won't work, but this issue was taken care of by #95. [...]
To test (on Android):
1. start the demo app
2. edit one of the known blocks such as paragraph or heading
3. wait a bit so Aztec makes the change signaling happen (at least 500 miliseconds ;) ) _this is something we'll probably need to take a look into at some point_
3. switch to HTML view
4. observe the html contents …
> HTML parser - restart datasource after full parse of html

- src/block-management/block-manager.js
_Supersedes already reviewed/approved #105 to clean commit history_
This completes a very draft, initial 1st iteration on implementing the inserter flow. With this, the flow goes roughly along the lines of the expected actions like this:
1. focusing on an item shows an item toolbar which for now currently includes the `+` button to insert a new item (this `+` trigger will be moved to the toolbar as per the designs https://github.com/wordpress-mobile/gutenberg-mobile/issues/58#issuecomment-409571383)
2. tapping on `+ ` makes a RN `Picker` show up
3. tap on the picker to choose the type of block you'd like to insert
4. a newly created block is inserted right below the block that was being focused on.
Known issues:
- the [RN `Picker`](https://facebook.github.io/react-native/docs/picker) …
> Inserter - show Picker with registered blocks to choose from

- .babelrc
- .flowconfig
- jest.config.js
- package.json
- src/parser/block-parser-code.test.js
- src/parser/block-parser-more.test.js
- src/parser/block-parser-paragraph.test.js
- src/store/index.js
- src/store/reducers/test.js
- yarn.lock
This PR:
* Fixes the `wp.coreBlocks.registerCoreBlocks is deprecated and will be removed in 3.8. Please use wp.blockLibrary.registerCoreBlocks instead.` warning by pointing to the `@wordpress/block-library` package
* Removes the `@gutenberg` alias from the Babel, Flow and Jest configurations
* Removed the `babel-plugin-module-resolver` mapping plugin as it's no longer needed 🎉
To test:
Run the app and tests and everything should work fine and without the warning about the `wp.coreBlocks.registerCoreBlocks` deprecation.
> Remove the babel module resolver

- package.json
- src/app/App.js
- src/app/App.test.js
- src/store/index.js
- yarn.lock
Fixes #121
This PR:
* Adds a test of the app with a block focused
* Fixes #121 by updating `react-test-renderer` to match the version of React. Solution inspired by https://github.com/facebook/react-native/issues/18222#issuecomment-370783271
To test:
1. Run the testsuite locally `yarn test` and notice it is green
2. Revert the `ae102a7` commit *locally* (`git revert ae102a7`) and run the testsuite again. That would show that the testsuite is broken (the test that tests the focused block) with #121 and so, the commit does fix the tests.
3. Remember not to push the branch with the revert ;)
> Test a focused block

- jest.config.js
Update GB hash to get latest changes about eventCount hidden to components, and fixed crash on H3, H4 blocks.
cc @SergioEstevao
> Update GB hash

- package.json
- rn-cli.config.js
- src/store/index.js
- yarn.lock
Parts of #140 . 
This PR implements the [changes on Gutenberg](https://github.com/WordPress/gutenberg/pull/9850) to recognize the image block.
To test:
- Update the Gutenberg submodule (should be pointing to `fc16864 `)
- `yarn clean`
- `yarn install`
- Check that the image placeholder is shown.
> Most basic image block

- src/store/index.js
This PR implements the[ changes on the `Gutenberg` project ](https://github.com/WordPress/gutenberg/pull/9888)to display the content of an image block, or the empty block UI. 
To be able to test them, this PR also adds an extra example block with an image to be displayed.
The buttons to add images do nothing. That's fine for now :) 
To test:
- Be sure that the Gutenberg submodule point to `06793a`.
- Run the project.
- Check that the UI looks like in the screenshot.
- Add a new image block.
- Check that the empty image block was added.
> Image Block: Adding example block with image.

- jest.config.js
- jest_gb.config.js
- package.json
- rn-cli.config.js
- yarn.lock
There was an update on GB that broke the native side.  Ref: https://github.com/WordPress/gutenberg/pull/9507
In this PR i've blacklisted `redux-routine` and made it working over NPM online.
> Update GB mobile and fix run-time red error screen with GB master

- .travis/travis-checks-js.sh
This PR adds an option to the Travis test script to specify whether to use the `test` yarn script or the `test:inside-gb` yarn script.
This will enable the nested-inside-Gutenberg setup to be used in Gutenberg's Travis flow as well.
To test A:
* Well, Travis should run on this and be green with all the tests running as before
To test B:
1. In a new fresh folder, clone the Gutenberg repo, change into it and checkout the `f8747043e` hash (it's the one this PR expects anyway)
2. Run `npm install` to install and compile packages
3. Change into the `gutenberg-mobile` subfolder
3. Run `GUTENBERG_AS_PARENT=true ./.travis/travis-checks-js.sh` and pay attention to the output. You should be able to find the `--config jest_gb.config.js` string somewhere, indicating that the mobile tests are using …
> Add option for Travis to run tests with GB as parent

- src/block-management/block-manager.js
This PR fixes the html text input that stoped responding to changes on Android.
**On iOS:**
If the html string is stored on the state and it changes, the whole TextInput is recreated, making jump on certain circumstances. (ref: #115)
**On Android:**
If the html string is **not** stored on the component's state, the state of the TextInput won't change even when the user tries. In other words, #115 broke Android's html TextInput.
This solution implements a different way to hold and get the html string for iOS and Android.
* I'm inclined to create an` HTMLTextInput` component that handles this problem internally, but I prefer to ask for suggestions before implementing it.
> Fix Android html text input

- symlinked-packages/@wordpress/escape-html
- symlinked-packages/@wordpress/rich-text
Title has it. 
Better to update to GB `master` asap, and test it well since new richText format already landed in GB. (Ref: https://github.com/WordPress/gutenberg/pull/7890)
> Update GB hash to latest master

- src/block-management/block-holder.js
- src/block-management/block-manager.js
This PR updates GB hash, and adds the code to insert a new para block after the current focused when enter.key is pressed.
There are few problems at the moment, not strictly related to this PR, explained below:
- `this.props.focusBlockAction( newBlock.clientId )` in `block-manager.js` is not working fine, the new block is not getting the focus, both if you tap `+` on the bottom toolbar and both if you press Enter.key in a para/heading block. cc @mzorz 
- There are problems getting the focus on blocks on Android, and consequence of this is that the bottom block management toolbar is not visible, and the index of the current block unknown. consequence of this is that I needed to add a hack to insert the block in the middle of the list atm.
GB side PR is available here: …
> Add a new empty para block on Enter.KEY

- src/components/html-text-input.js
This was a regression from (I think) updating `react-native`.
Some internal on how the TextView works on iOS broke our (hacky) HTML editor implementation.
The original problem look like this:
Now if we set a value directly to the TextInput component, and we don't let it re-render, the component will keep that state not allowing editions:
This PR solves that problem by setting the TextView text value directly using a reference.
@marecar3 Could you please take a look at this?
To test:
- Run the project on iOS
- Check that the HTML Editor behaves normally.
> Fix: html editor

- src/app/App.js
- src/app/App.test.js
- src/app/initial-html.js
- src/store/index.js
This PR allows the app to receive the initial html content via the initial props React Native is passing when bootstrapping the app. This enabled passing an initial post content via a parent app when the RN app is embedded.
Running the app as normal should work OK with the usual demo content coming up when ran.
Tests should also pass green.
* clone the WordPress Android app from git@github.com:wordpress-mobile/WordPress-Android.git
* cd into the cloned repo check out the `feature/integrate-gutenberg` branch
* in the terminal again, `git submodule update --init` to pull the mobile Gutenberg codetree
* cd into the mobile Gutenberg tree (`libs/gutenberg-mobile`) and as normal, do `git submodule update --init`, `yarn install` and `yarn start` to start Metro
* open the wpandroid project in …
> Accept initial content via the root props

- src/block-management/block-holder.js
- src/store/index.js
Youhou my first PR on the mobile repo. I don't really know how to test it at this stage but let me know how it looks.
The idea is to replace the deprecated APIs that are going to be removed from the Gutenberg repository.
Thanks for you help.
Related https://github.com/WordPress/gutenberg/pull/10952
> Avoid using the setUnknownTypeHandlerName deprecated APIs from Gutenberg

- src/app/App.test.js
This was causing an error in a Gutenberg PR https://github.com/WordPress/gutenberg/pull/10952 but I wonder why it didn't fail in this repository before.
> ESLint: Avoid focused unit test

- package.json
- yarn.lock
When I installed yarn in my new laptop I got the latest version (1.10) which
adds an integrity field to each entry in yarn.lock
I ran `yarn install` and by suggestion of @diegoreymendez added the specific
yarn version to the `engines` section in `package.json`, so yarn will prompt you
to upgrade if you use an older version
> Updated yarn to 1.10.1

- src/block-management/block-manager.js
- src/store/reducers/index.js
This PR is a proposal to fix an issue on iOS when selecting a `paragraph` block and creating a new block from it:
We use `findDataSourceIndexForFocusedItem` to get the index of the focused block and insert the new block below it.
`findDataSourceIndexForFocusedItem` use `this.state.dataSource` to get the block state, and I noticed that the `focused` state of the focused block was `false`. But the same block had `focused` state `true` on `this.props.blocks`.
Using `this.props.blocks` instead of `this.state.dataSource` on iOS solved the problem.
This still feels like a workaround other than finding and fixing the real problem. Hopefully @tug 's work on Gutenberg internal state will fix this more permanently 😁
To test:
- Run the iOS example app.
- Select a paragraph block.
- Tap on the + …
> Fix error on iOS when adding a new block from paragraph block.

- android/app/build.gradle
- android/build.gradle
Currently you might see the following error when running `yarn android`:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'gutenberg'.
> Could not resolve all files for configuration ':classpath'.
> Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar
```
This PR should fix it.
- Install `gutenberg-mobile` from scratch
- Install Android Studio 3.2
- Run `yarn install`
- Run `yarn android`
> Fix maven dependency error with Android Studio 3.2

- src/store/reducers/index.js
Fixes #190 
Tapping twice on the same block no longer removes focus from it.
Just tap multiple times in the same text block and make sure the bottom toolbar is never removed.
> Tapping twice no longer removes focus.

- package.json
With latest [PR](https://github.com/WordPress/gutenberg/pull/11255/files) on gutenberg, we have experienced failing builds on our end. This quick fix will catch up us with gutenberg and our builds will pass with success.
> Added turbo-combine-reducers dependency to fix failed builds

- yarn.lock
Small PR to commit the yarn.lock entry for `turbo-combine-reducers`.
This is automatically added by running `yarn install`.
To test:
- `yarn install` should not modify any file.
- Everything should run just fine. ✨
> Adding yarn.lock entry for `turbo-combine-reducers`.

- package.json
- yarn.lock
This PR follows up #201 and merges to master the updated refs to `react-native-aztec` and `react-native-recyclerview-list`.
The changes where tested via #201 , https://github.com/wordpress-mobile/react-native-aztec/pull/66 and https://github.com/wordpress-mobile/react-native-recyclerview-list/pull/9
> Use wpandroid compat aztec and list

- src/app/App.js
- src/block-management/block-manager.js
- src/block-management/block-toolbar.js
- src/block-management/constants.js
- src/block-management/inline-toolbar.js
Addresses part of #58 
Adds a bottom toolbar button to trigger the Inserter. This is the minimum needed in order to be able to add a block when no block is selected or there are no blocks at all (e.g. when a new post, which is part of #182)
Changes in this PR:
1. Allow for empty string as initial data from the parent app
2. Inserter button in the bottom toolbar
3. Removal of inserter button from the inline toolbar
Scope not handled by this PR:
* Styling of the Inserter button to match https://github.com/wordpress-mobile/gutenberg-mobile/issues/58
To test 1:
* Run the app. No blocks are focused yet.
* Tap on the bottom toolbar Inserter button
* Select a block from the Inserter bottom sheet
* Scroll at the beginning of the content and notice the new block is there
To test 1:
* Run the app. …
> Inserter button in toolbar

- react-native-gutenberg-bridge/RNReactNativeGutenbergBridge.podspec
This PR improves the integration with a parent app by declaring the dependencies needed by Gutenberg-Mobile in the `react-native-gutenberg-bridge` podspec.
**To test:**
Follow the instructions in the WPiOS integration PR.
https://github.com/wordpress-mobile/WordPress-iOS/pull/10445
> [Bridge iOS]: Better bridge podspec

- src/block-management/block-picker.js
This PR adds the behavior to dismiss the block-type picker modal when the user taps `back` on Android without needing to touch outside the modal or swipe it down.
First reported by @daniloercoli .
To test:
1. open the demo app on Android
2. tap on the `+` inserter button
3. tap `back` 
4. observe the modal is dismissed.
> Fix Android back button not dismissing the inserter's block-type picker

- package.json
- src/app/AppContainer.js
- yarn.lock
https://github.com/wordpress-mobile/gutenberg-mobile/pull/226 caused a regression in the js to native bridge. We're not sending the `changed` parameter anymore when calling `provideToNative_Html`. This PR fixes it.
> Note: it's currently causing a problem in https://github.com/wordpress-mobile/WordPress-iOS/pull/10461 when you tap "Publish" on parent app it crashes.
> Send `changed` to the native bridge if html changed since last time

- ios/gutenberg.xcodeproj/project.pbxproj
I just went to the Xcode project and changed the target from iPhone to Universal
> Make gutenberg-mobile universal so it works on iPad

- src/app/App.js
This PR reestablish possibility to pass initial data from a parent app.
As a bonus, on iOS it's now possible to send an empty string as initial data and we will get an empty post instead of the example post. (Not tested on Android)
**To test:**
- Check that the example app displays as always.
**On WPiOS:**
- Checkout https://github.com/wordpress-mobile/WordPress-iOS/pull/10467
- Check that posts from the post list open the proper post data.
- Check that a new post opens an empty post.
> Reestablish possibility to pass initial data from a parent app

- src/app/AppContainer.js
This PR recovers the functionality that insert a new block at the end, if no block is selected.
To test:
- Remove all blocks from the post.
- Add a new block.
- Switch between HTML and Visual mode to deselect the previously created block.
- Create a new block. 
- Select the block at the top.
- Create a new block.
> Recover insert block at the end, if no block is selected.

- src/block-management/block-picker.js
This fixes an issue with the inserter's Block-Type picker that would not respond to touch at first touch when the focus was taken by a PlainText-backed block such as `Code` or `More` (implemented with InputText in React Native).
Before:
(it's difficult to see, but believe me I had to tap twice :D - you'll be able to reproduce following the steps below).
After:
**To test:**
1. open the demo app
2. tap into a `Read More`  or `Code` block
3. observe the cursor appears and keyboard goes up
4. now tap on the inserter icon `+` 
5. see the block type picker appear
6. tap on any icon
7. observe it responds to touch at first touch.
> Fix Picker touch handling, avoiding to have to touch twice if unfocused

- package.json
This add v10 and above to the list of allowed node engines to work with this project.
We haven't yet defined a fixed version of node to use, so in the meantime let's be permissive and just exclude the engines we know don't work (v9).
> Allow node v10 engine in package.json

- .flowconfig
- jest.config.js
- package.json
- symlinked-packages-in-parent/@wordpress/html-entities
- symlinked-packages/@wordpress/html-entities
- yarn.lock
This PR attempts to fix the `simple-html-tokenizer` changes in `@wordpress/blocks` that are making our test fail when upgrading `gutenberg` to `master`:
```
/home/travis/build/wordpress-mobile/gutenberg-mobile/node_modules/simple-html-tokenizer/dist/es6/tokenizer.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import EventedTokenizer from './evented-tokenizer';
^^^^^^
SyntaxError: Unexpected token import
29 |  */
30 | const REGEXP_WHITESPACE = /[\t\n\r\v\f ]+/g;
> 31 | 
32 | /**
33 |  * Matches a string containing only whitespace
34 |  *
at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
at Object.<anonymous> (gutenberg/packages/blocks/src/api/validation.js:31:41)
at Object.<anonymous> …
```
> Fix simple-html-tokenizer changes in `@wordpress/blocks` breaking our tests

- src/block-management/block-manager.js
- src/block-management/block-picker.js
This PR fixes an issue on iOS where the currently focused TextField looses focus when the `BlockPicker` component is dismissed.
Before:
Notice the cursor how it jumps to the previously focused block.
Fixed:
The code changes seems unrelated to TextField focus. It took some digging but the reason is this:
For some reason, the dismissing of the modal triggers (sequentially) the unfocus of the textfield.
This happens using the `isVisible` functionality of the `Modal` component. So showing and hiding the component like "any other" made the trick.
This is probably a React-Native bug.
@mzorz , since you are working on focus issues, could you take a look at this? :)
Thank you!
> Removing `visible` prop from `BlockPicker`.

- .gitignore
- bin/generate-podspecs.sh
- react-native-gutenberg-bridge/third-party-podspecs/DoubleConversion.podspec.json
- react-native-gutenberg-bridge/third-party-podspecs/Folly.podspec.json
- react-native-gutenberg-bridge/third-party-podspecs/React.podspec.json
- react-native-gutenberg-bridge/third-party-podspecs/glog.podspec.json
- react-native-gutenberg-bridge/third-party-podspecs/yoga.podspec.json
This ensures that the app will always fetch the React Native podspecs matching the React Native version used.
To test, you can check out the other PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10505
> Store 3rd party podspecs in the repo

- src/app/AppContainer.js
This is a fix so post aren't marked as dirty when the resulting HTML remain unchanged.
This is a follow up fix for https://github.com/wordpress-mobile/gutenberg-mobile/pull/242
> Intialize with the raw post html to avoid marking posts as changed when no changes were made

- src/block-management/block-picker.js
Letting the modal library use the default animation looks similar to me and
fixes the issue where the translucid background also slides in.
> Fix modal animation

- src/block-management/block-manager.js
This PR switches the main blocks list to ReactNative `FlatList` component on Android.
- The switch back to FlatList was required since there are issues selecting text in any of the blocks in the list. The issue is not limited to AztecWrapper powered blocks, such as Para and Heading, but it's affecting the code block that is backed by `TextInput`.
- There are also problems with the contextual menu that does appear on the screen. There is no wat to paste or copy text at the moment.
I've spent some time trying to fix the issue in our recycler view list repo, with no luck.
It's not clear to me why we've selected this custom list component (beside animations), since ` FlatList renders items lazily, just when they are about to appear, and removes items that scroll way off screen to save memory …
> Use FlatList instead of our custom recycler view list on Android

- src/app/AppContainer.js
- src/block-management/block-toolbar.js
Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/171
Requires Gutenberg changes https://github.com/WordPress/gutenberg/pull/12231
This PR adds the undo and redo feature to the block toolbar, right next to the add block button:
For this we simply import the right components from the `@wordpress/editor` Gutenberg package.
> Add undo redo

- src/block-management/block-holder.js
This PR fixes an issue where tapping on a `PlainText` or `AztecWrapper` block does not make the bottom bar following the focus, and be visible attached to the correct block. #251
It seems that the problem was related to the `onFocus` method not properly propagated up in the software layers, and our data model was lagging one step behind the focus. 
Companion GB PR is here: https://github.com/WordPress/gutenberg/pull/12316
To test:
- Tap on a `Para` block and check that the toolbar is visible
- Tap on a `Code` block and check that the toolbar is visible
- Tap on a `More` block and check that the toolbar is visible
> Fix block toolbar that sometime doesn't appear when the block get the focus

- src/app/AppContainer.js
- src/block-management/block-holder.js
- src/block-management/block-manager.js
This PR adds ability to listen on the focus lost event / onBlur so that we can unselect the block => clear the selected block =>  dismiss the block toolbar.
To test this PR:
- Tap on a para block
- The bottom toolbar is visible together with the keyboard
- Tap on page break block
- The bottom toolbar is NOT visible, nor the keyboard
- Tap on a code block
- The bottom toolbar is visible together with the keyboard
- Tap on an unsupported block
- The bottom toolbar is NOT visible, nor the keyboard
GB side PR available here: https://github.com/WordPress/gutenberg/pull/12370
Note: there are still minor issues in the editing flow, like the keyword is dismissed when it should not. Or to start editing into a block you need to tap it twice or three. Will report this issues on …
> Add the ability to react to focus lost and change the UI accordingly 

- src/app/AppContainer.js
- src/block-management/block-holder.js
- src/block-management/block-manager.js
This PR does fix a problem where the Toolbar is unusable when the `onBlur` event is connected, and used to deselect the current block. 
Problem introduced in this PR here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/283
Un-wiring the `onBlur` took us one step back but makes the toolbar usable again.
The whole `onBlur` infrastructure/code is kept in place for future usage.
> Un-wire `onBlur` and make the Toolbar working again

- src/block-management/block-manager.js
Another take at #291. Most of the changes are in https://github.com/wordpress-mobile/react-native-aztec/pull/84 but this also sets `keyboardShouldPersistTaps` to `always` in the `FlatList`.
The default behavior had FlatList blurring field every time you tapped outside them, which meant they were being blurred twice and losing the keyboard.
To test, follow the steps in #291, and confirm the keyboard stays up. A known issue is that if you tap on a non-text block (image, unsupported), the current text field will keep focus, but that's a different task in #197
> Persist keyboard as you switch from one block to another

- src/block-management/block-manager.js
The test text was good for debugging, but new blocks should be empty by default
> Create blocks empty by default

- .eslintrc
Updating gutenberg subrepo ref to include 
WordPress/gutenberg#12409, WordPress/gutenberg#12422 from https://github.com/wordpress-mobile/WordPress-iOS/issues/10569
> Update gutenberg subrepo ref

- .travis.yml
This PR removes the automatic generation and upload of the iOS JS bundle on Travis since the iOS side of the integration is not using it.
While at it, it removes the dedicated Travis job and piggybacks on the Android tests jobs for faster total time.
To test:
Check out the Travis build and notice only 3 jobs are there. Also notice that the Android job has building and uploading of the JS bundle artifact.
> Create the Android JS bundle only on Travis

- src/app/App.test.js
- src/app/AppContainer.js
- src/block-management/block-holder.js
- src/block-management/block-manager.js
Requires https://github.com/WordPress/gutenberg/pull/12434
This PR adds a default text in the content area when no blocks are available. Clicking on it will replace it with an empty paragraph block by default.
This is close to what's available in the web version with with `BlockListAppender` even though it's simpler at this stage.
You can test this without using the parent app if you manually set `initialHtml` to `""` (empty string).
For instance in `App.js`: 
```
<AppContainer initialHtml="" />
```
> Show default block appender component when post is empty

- jitpack.yml
Adds `--stacktrace` to the Jitpack gradle build for better error reporting.
> Enable more error reporting in gradle in Jitpack

- src/block-management/block-toolbar.js
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/317
The block toolbar is made scrollable horizontally. If the scrollbar content is smaller than the scrollbar itself then it won't scroll, thus, it won't scroll for blocks other than Heading right now, but in the future if other blocks have also lots of toolbar buttons then it will scroll also for them with no extra effort.
**To Test:**
- Add a Heading block and type something in it
- Verify that scrolling horizontally is possible
- Verify that you can tap toolbar buttons with no problem
> Make toolbar horizontally scrollable

- ios/gutenberg/GutenbergViewController.swift
This PR fixes a syntax error found on Xcode 9.
To test:
- Launch the project using Xcode 9.
- Build and run.
- Check that there are no errors.
> [iOS] Fix syntax error on xcode 9

- yarn.lock
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/320
Requires https://github.com/WordPress/gutenberg/pull/12608
This PR fixes a regression on SVG styling I introduced in https://github.com/wordpress-mobile/gutenberg-mobile/pull/310.
- Boot the app on ios and android
- Check that the buttons are not black but light gray
> Fix SVG styling

- react-native-gutenberg-bridge/android/build.gradle
The PR adds a "manual" wait for waiting JitPack to finish producing the artifacts for `react-native-aztec`.
The idea here is to "inject" the wait to the dependencies that change often or seem to take enough time to get produced that Gradle times out.
The "juice" lives in a function published on a gist here: https://gist.github.com/hypest/f526fe0775dedce0ce0133f1400d22a4. The git history of developing that function is in the current PR's history of commits.
Even though we could probably just get away with increasing Gradle's HTTP timeouts as suggested on [JitPack's FAQ](https://jitpack.io/docs/FAQ/), that would increase timeouts for all requests made by Gradle, with unexpected results. Instead, this PR tries to limit scope by prolonging the "wait" only for a specific artifact.
To test:
0. …
> Wait JitPack to produce react-native-aztec's artifacts

- react-native-gutenberg-bridge/android/build.gradle
Similar to https://github.com/wordpress-mobile/react-native-aztec/pull/91, this PR prioritizes the JitPack maven repo over the NPM CDN's ones, uses jsdelivr.net as the CDN and additionally, it employs the `waitJitpack()` Gradle helper function to wait on all the JitPack builds for the React Native subprojects.
The `waitJitpack()` was previously reviewed in #333.
To test:
1. Change into the `react-native-gutenberg-bridge/android` subfolder
2. Run `./gradlew assemble` to build the bridge library
3. The build should suceed and two `Will use the jsdelivr.net exposed maven repo at ...` log output lines should appear, one for `react-native` and one for `jsc-android`
> Prioritize JitPack over the NPM CDN and wait on all RN subprojects

- src/block-management/block-manager.js
Comes from https://github.com/wordpress-mobile/gutenberg-mobile/pull/327#discussion_r
While PR #327 addresses #315 description, it's been observed that desired behavior is more that of following along Gutenberg web as much as we can. @koke observed the behavior should be closer to Gutenberg's by using `isUnmodifiedDefaultBlock` (see https://github.com/WordPress/gutenberg/blob/40d1282a992702e1933118ef626f0666692baf2b/packages/editor/src/components/inserter/menu.js#L389)
**Please note** that this makes the _default block_  (currently, `core/paragraph`) the only block type eligible for replacement when such a block is both empty and selected, and the user taps on + to bring up the inserter's block picker.
With this PR then, if the user is standing on an empty `Heading` or  `Code` block, they …
> use same behavior as Gutenberg web for replacing an empty default block

- package.json
- react-native-gutenberg-bridge/android/build.gradle
- yarn.lock
This PR:
- Upgrades to v8.0.9 of `react-native-svg`, needed to make the android build work (otherwise gradle complains with `Could not find com.android.tools.build:gradle:2.2.3`
- Start using the forked library, now at https://github.com/wordpress-mobile/react-native-svg, and especially the `feature/enable-android-build-of-standalone-package` branch. Background: we need to maintain the fork for now to have support for building `react-native-svg` as a standalone library via JitPack, used in the binary build pipeline of wpandroid ([See here](https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/react-native-gutenberg-bridge/android/build.gradle#L82)).
To test:
* Run the demo app and notice that the various icons are working as before
> Upgrade react-native-svg to v8.0.9, use the forked lib

- src/block-management/block-toolbar.js
Fixes #354 
This PR adds `SafeAreaView` to the toolbar to make it aware of iOS Safe Areas.
To Test:
- Build and run the iOS example project.
- Check that the tool bar is over the bottom safe area (as shown in the image).
- Tap on a block to show the keyboard.
- Check that the tool bar is still properly visible.
This should not affect Android.
- Check that Android toolbar is unchanged.
> Adding SafeAreaView to block-toolbar component.

- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
This is necessary to solve #357 
The idea is to let the delegate knows when the Gutenberg module has finish loading.
There was an issue before when we try to show the keyboard on load, that the toolbar wasn't showing. That is because the keyboard was shown before the gutenberg module had time to finish loading.
Using this method, we can present the keyboard safely.
To test:
- Clean build folder of example app.
- Build and run the example app.
- Check that there are no errors.
- Follow the instructions from https://github.com/wordpress-mobile/WordPress-iOS/pull/10654
> Adding gutenbergDidLoad to iOS Bridge.

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- src/app/App.js
- src/app/AppContainer.js
This PR adds support for setting the html/visual mode upon start-up. A flag passed down via the top-level props is used to signal this.
To test:
* Need to test this via the wpandroid app. Use this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/8778
> Initial flag for html mode

- README.md
Noticed another typo which I didn't see/address in #384 (sorry!) , "Prerequisities" should read as "Prerequisites".
> README Typo: "Prerequisities" --> "Prerequisites" 

- src/block-management/block-manager.js
This PR adds a `SafeAreaView` to block-manager content. This makes the content aware of iOS safe areas.
The use of `SafeAreaView` should not affect Android in any way.
To test:
- Run `yarn ios` (it should open a iPhone X simulator)
- Set the simulator on LandScape.
- Check that the content looks like in the screenshot.
- Check that the same is true for the HTML view.
> [iOS]: Make post content aware of Safe Areas.

- react-native-gutenberg-bridge/ios/Gutenberg.swift
This PR adds a `isLoading` public variable to the iOS Gutenberg bridge.
Needed for this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10674
To test:
- Refer to the previously mentioned PR.
> [Bridge iOS]: Adding isLoading public variable.

- src/components/keyboard-aware-flat-list.android.js
- src/components/keyboard-aware-flat-list.ios.js
This PR re-arranges the scrolling offset of text inputs for landscape mode.
We are showing the inner toolbar in portrait mode but in landscape mode we don't have room for it so we won't show that.
Before:
After:
Fixes part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/197
**To Test**
Test 1 - Landscape mode
- Open a blog post on WPiOS app
- Switch to landscape mode
- Add one of the text input blocks with the return button on keyboard
- Verify that focused field is viewable
- Add one of the text input blocks with (+) button
- Verify that focused field is viewable
- Close the keyboard, focus again on one of the text input blocks
- Verify that focused field is viewable
Test 2 - Portait mode
- Open a blog post on WPiOS app
- Switch to portrait mode
- Add one of the text input …
> iOS Only - Re-arrange scroll position of text inputs on landscape mode

- react-native-gutenberg-bridge/index.js
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
- src/app/App.js
- src/block-management/block-manager.js
- src/block-management/block-toolbar.js
This PR is meant to solve a problem on iOS, where the toolbar is wrongly positioned when is automatically presented on load (WPiOS)
https://github.com/wordpress-mobile/gutenberg-mobile/pull/386 Added a `SafeAreaView` to `block-manager`. This affects the layout calculations but it's normally not a problem.
The problem happens when we try to present the toolbar before that calculation is resolved (before onLayout is called).
The idea of `editorDidLayout` is to let the Native side know when this happens, so it can present the keyboard at an appropriate time, so the toolbar displays correctly.
Check https://github.com/wordpress-mobile/WordPress-iOS/pull/10682 for more info and how to test it.
> Sending `editorDidLayout` message to Native Bridge side.

- .eslintrc
- src/app/App.js
Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/398
This PR unregisters `Code` and `More` for the prod build.
- Run locally using `yarn start` and `yarn android` or `yarn ios` and notice the Code and More blocks are visible
- Run a Release build with `node_modules/.bin/react-native run-ios --configuration Release` and notice the Code and More blocks appear as unsupported blocks.
> Disable Code and More blocks for release

- .flowconfig
- flow-typed/TextInputState.js
- src/block-management/block-holder.js
This PR fixes #308 for the Alpha, by dismissing the keyboard (calling blur on the last TextInput field) when the field that now gets the focus is a non-textual field.
Please test extensively on iOS, and Android.
> [Alpha] Hide the keyboard when tapping on non-inputField block

- src/block-management/block-holder.js
- src/block-management/block-holder.scss
Fixes #393 
Removes the top/bottom padding on `block-container` as it was adding an unneeded extra space.
Before:
After:
Before (WPAndroid):
After (WPAndroid):
Before (demo app on iOS):
After (demo app on iOS):
> Remove block top/bottom padding

- src/block-management/inline-toolbar/style.scss
> Add 2px left and right margins to inline toolbar

- src/block-management/block-holder.scss
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/402
Left&Right borders are currently viewable on iPhone X generation devices & landscape modes but other types of devices and portrait mode should also be tested to make sure it doesn't have unwanted consequences.
Left&Right borders should appear on the focused block as below:
Portait mode shouldn't change.
**Testing**
- The borders on the focused block:
- should be visible in iPhone X generation devices in Landscape mode.
- should not be visible in Portrait mode, although they still do exist on Portrait mode we should check that they are hardly noticeable.
- Android side also should be checked to verify right&left borders are hardly noticeable in Portrait mode.
> Add left/right borders to focused block

- package.json
- react-native-gutenberg-bridge/android/build.gradle
- yarn.lock
Currently we use the jsdelivr.net CDN as a pseudo maven repo to fetch React Native when building form source.  This has caused some issues, including repeated failed builds. An issue for this is here: https://github.com/wordpress-mobile/WordPress-Android/issues/8783
This PR solves this by replacing our usage of the CDN with an actual Maven repo where we are mirroring the React Native dependencies. I will follow up with another PR to automate uploading to that repo when we update React Native.
The maven repo is here: https://bintray.com/wordpress-mobile/react-native-mirror
Related PRs:
- https://github.com/wordpress-mobile/react-native-aztec/pull/100
- https://github.com/wordpress-mobile/react-native-recyclerview-list/pull/13
- https://github.com/wordpress-mobile/react-native-svg/pull/1 …
> Use Bintray mirror of RN when not building from source

- src/block-management/block-toolbar.js
- src/components/keyboard-hide-button.js
This PR creates a `KeyboardHideButton` component that renders the proper hide-button icon using the RNSVG library.
This is a temporary change since we should ultimately use `dash-icons` with the `ToolbarButton` component.
**Notes:**
The original .svg file for the icon seems to be too complex for RNSVG, so I redrew it with simple shapes.
To test:
- Run the example app.
- Tap on a textual block to show the keyboard.
- Check that the new icon shows correctly.
- Tap on the hide-keyboard button.
- Check that the keyboard hides.
cc @koke
> Adding KeyboardHideButton component.

- __mocks__/styleMock.js
- src/components/keyboard-aware-flat-list.ios.js
This change fixes the bottom padding of the focused block to the keyboard. There was a small extra padding left after this PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/399 so we are fixing that by importing the new value.
Before:
After:
**To Test**
- Run yarn start
- Open WPiOS app in debug mode and open a post
- Add more than 5-6 paragraph blocks so that the content size exceeds the screen size
- Tap one of the block at the bottom of the page
- Verify that the scrolling position doesn't have unnecessary padding between the keyboard and the bottom of the focused block.
> iOS only - Fix bottom padding of focused block to the keyboard

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
It seems that RN doesn't like it when we start early and then re-set the
app props very soon after. So, instead, starting the RN app later, as
soon as we get the post content via `setContent()`.
This PR probably fixes #390 too.
To test:
1. Use the web to create a post that uses the demo content from https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/app/initial-html.js
2. Use wpandroid `zalphaRelease` (remember to enable Gutenberg from App settings)
3. Open the post and notice the content loading normally
4. Try going back and opening the post more than a few times. It should always open normally.
> [Android bridge] Start the RN app only after we got the real post content

- src/block-management/block-manager.js
Fix #439 
This PR checks whether the selected block is replaceable and only shows the ADD BLOCK HERE when it is _not_ going to be replaced.
Also, we're using the i18n API now for the `ADD BLOCK HERE` string.
> only show Add Block Here indicator when block is not replaceable

- src/block-management/block-manager.js
- src/block-management/block-picker.js
Fix #452 
This PR drops the ` isReplacement`  prop from the BlockPicker and always shows:
- block picker title "ADD BLOCK" , dropping "REPLACE BLOCK" 
**IMPORTANT** This PR assumes we will also work on #453
> Block Picker: remove 'replace block' title, only keep 'add block' title

- android/build.gradle
Aztec was sending a "backspace" as part of process of cleaning up the text to paste a new one, but that triggered the merge logic in the context of Gutenberg.
This PR points to the fix. PR on the react-native-aztec side: https://github.com/wordpress-mobile/react-native-aztec/pull/107
To test:
1. In the demo app, select and copy some text from a paragraph block (e.g. select the "World" from the `Hello World` paragraph block
2. Place the cursor at the end of the paragraph block and tap "Enter" to create a new block
3. Long tap and paste the text. It should work.
This PR will get updated when the react-native-aztec PR gets merged.
> Fix for disappearing block on paste

- README.md
Noticed a link wasn't working, so this PR proposes updating it to one which _does_ work, but I'm not sure if that's the place it's supposed to redirect to? Also fixes a typo where an extra "the" is present.
New link: https://github.com/react-community/create-react-native-app/blob/fc1ef3c74626191ad4c610cc57cc8ebe97104021/react-native-scripts/template/App.test.js
> README: Update Link & Typo

- src/block-management/block-manager.js
- src/components/html-text-input.js
- src/components/html-text-input.scss
Fix https://github.com/wordpress-mobile/gutenberg-mobile/issues/429
This PR fixes the KeyboardAvoidingView issue on iOS and makes the html editor avoid keyboard. Edge cases aren't tested because this issue is low priority for beta, it is just a fix to make it better than the current version.
**To Test**
Testing prerequisites
For WPiOS
Checkout the PRs branch to any arbitrary folder and cd .. to it
run yarn install, yarn start
Open XCode WPiOS on the latest develop
Clean build folder on Xcode, and then run the app
For WPAndroid
open grade.properties at WordPress-Android folder
add wp.BUILD_GUTENBERG_FROM_SOURCE = true to grade.properties
checkout the PRs branch in the subrepo of WordPress-Android repo
cd to WordPress-Android/libs/gutenberg-mobile
run yarn install, yarn start
yarn wpandroid …
> HTML Editor - Fix keyboard avoiding behavior on iOS

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Adds the required additions to implement the title in RN for Gutenberg in Android.
The base branch of this PR is the main feature branch `issue/372-add-title-to-gutenberg-mobile`.
Parent PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/450
WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/9027
1. Run the app.
2. Edit the title and make sure the state is properly maintained.
3. Tap save.
Check the console log that the title is properly retrieved.
1. Run the app.
2. Delete the title and make sure the placeholder is shown.
> Android - Add post title to Gutenberg Mobile

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #438 
This is a small PR that forces layout when the user paste text. I noticed that `layoutSubviews` is called every time `textViewDidChange` is called, except for pasted text. Adding an explicit call to `setNeedsLayout()` solves the issue.
I tested that `layoutSubviews` is not called more than once for every text change, and now it's properly called after pasting text.
**To test:**
- Test pasting a long text in a paragraph block.
- Check that its heights grows accordingly.
> Make Aztec send height information to JS after pasting text

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/9099  by using `setContent` instead of `initContent` when initializing WPAndroidGlue code.
`setContent` has a guard to prevent the double init of the React Application.
> [wp-android] Fix crash starting writing new post

- ios/gutenberg/GutenbergViewController.swift
- ios/gutenberg/Info.plist
- ios/gutenberg/MediaPickAndUploadCoordinator.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Refs #471 
This PR hooks the methods needed to get the device camera capture of media.
> Upload captured photo ios

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
This PR fixes #503  by making sure that both title and content have been set before starting the RN app.
(Legacy editor(s) implementation had the two as separate calls but, we only want a single call to correctly boot the GB editor).
Steps to Test:
- Open a post from posts list
- Exit from the editor
- It's NOT marked as changed
Steps to Test on new post:
- Start a new post
- Exit the editor without typing in it
- It should not upload the draft
WP-Android companion PR here: <link still missing>
> Fix the changes detected issue on Android

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
This PR adds the needed interfaces to make Gutenberg start receiving upload progress updates when it's shown on the screen, for images that exist within the open Post that are currently being uploaded.
This can be tested with the WPAndroid PR https://github.com/wordpress-mobile/WordPress-Android/pull/9129
Related Gutenberg PR:
https://github.com/WordPress/gutenberg/pull/13516
- refactored the `MediaUploadCallback` implementation a bit as it's needed to be passed to 3 interfaces  (`onCapturePhotoPressed`, `onUploadMediaPressed`, and now also `onImageQueryReattach`)
- this new interface allows the listener to be set on the bridge, updates were already being listened to
- also, the hosting app can start sending latest max progress updates once the Image component calls the new interface …
> Media upload progress reattach android

- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/index.js
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
This PR implements the interface on GB-mobile for resync of uploads in iOS.
You can test this on the demo app, by switching to HMTL and back to visual. 
On this demo app we don't any need special code because of the simulation of events is done using timers.
@mzorz I will save the renaming of the method for a separate PR, where I will rename other media methods to keep them more consistent.
> Media upload reattach on iOS

- src/block-management/block-manager.js
- src/block-management/block-manager.scss
Removes the border from the title and changes the placeholder text to match what's described [here](
https://github.com/wordpress-mobile/WordPress-iOS/pull/10794#issuecomment-455329479).
Closes https://github.com/wordpress-mobile/gutenberg-mobile/issues/372
Make sure the title has no bottom border.
Remove the title from the demo and make sure the placeholder reads "Add a Title".
1. Edit the title
2. Switch to HTML and back.
Make sure the edits are properly persisted.
> Removes border from title and changes the placeholder text.

- react-native-aztec/README.md
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
We've added some changes to `ReactNativeAztec` that were not merged back into the subtree in gb-mobile. 
See https://github.com/wordpress-mobile/react-native-aztec/pull/114
I've NOT squashed the commits. Maybe we want to use that feature in the future to avoid commits in out history here.
> Update ReactNativeAztec subtree

- src/block-management/inline-toolbar/index.js
This PR implements the changes made on https://github.com/WordPress/gutenberg/pull/13597 to display inline toolbar buttons declared by each block.
On this particular PR, the `Images settings` button will be displayed, towards the task described here: 
https://github.com/wordpress-mobile/gutenberg-mobile/issues/202
To test:
- Run the project.
- Select an Image block with an image.
- Check that the settings button is displayed like in the screenshot.
- Select an empty image block.
- Check that the settings button is not there.
> Implementing InspectorControls.Slot for inline toolbar buttons.

- .travis.yml
- jitpack.yml
- react-native-gutenberg-bridge/android/build.gradle
This PR removes the dependency on Travis+AWS to produce the Android JS bundle and instead, tasks JitPack to produce and include the JS file inside the Bridge library's assets folder. The parent app can then access the file automatically because of resources merging.
h/t to @jtreanor for the assets bundling idea!
To test:
Use this wpandroid side PR: https://github.com/wordpress-mobile/WordPress-Android/pull/9156
> Bundle the Android JS file inside the bridge lib

- ios/gutenberg/MediaUploadCoordinator.swift
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
This PR makes sure that in iOS we only send events when someone is observing on the JS side.
> Only send events if observing

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes an issue that was causing the title font to be wrong, if emptied (or when creating a new post in WPiOS).
Also fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/563
1. Empty the title
2. Make sure the placeholder font and vertifcal alignment look fine.
3. Switch to HTML mode and back and make sure the title's font is right.
> Fixes an issue with the font in the title and placeholder for the title.

- react-native-gutenberg-bridge/third-party-podspecs/react-native-keyboard-aware-scroll-view.podspec.json
This change updates react-native-keyboard-aware-scroll-view version in 3rd party podpecs.
Can be tested with PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10968 Actually it'd be enough if that PR passed buddybuild
This should have been a part of PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/554 but it was forgotten.
> Update react-native-keyboard-aware-scroll-view in 3rd party podpecs

- android/app/build.gradle
- android/app/src/main/java/com/gutenberg/MainApplication.java
- android/settings.gradle
We haven't made an effort to augment the Android demo app to support the bridge interface since that could be tested directly with the main WP app. We avoided having code directly call any of the bridge functions without responding to a request _from_ the bridge anyway.
With #587 though, we have the editor send up an event upon initializing/mounting, and that requires the bridge to be in place to work on Android. This PR adds that support.
Test do fail in this PR because the Jest is missing a mock for `editorDidMount()`. After all, the bridge is still not there for Jest anyway so, we need to mock it. Leaving this change for the parent PR though since it's not related to this PR.
To test:
* Run the demo app. It shouldn't red-screen complaining that `editorDidMount` is missing from the …
> Support for the bridge in the android demo app

- src/block-management/block-toolbar.js
- src/block-management/block-toolbar.scss
- src/index.js
Fixes #380 
This PR fixes two issues related to RTL layout.
**1. The block Toolbar on Android:**
The content of the scroll view on Android was aligned left, while on iOS it was correctly aligned right. Probably the issue has little to do with alignment itself but on how each platform rotate scroll view for RTL support.
This was fix by forcing the content to grow as big as the scroll view itself (allowing it to grow bigger if necessary).
**2. BottomSheet text input:**
Fixed in the `gutenberg` related PR (https://github.com/WordPress/gutenberg/pull/13815)
This was an issue since we are inverting the natural alignment for text inputs, so we had to express this intention on RTL layout too. Sadly `text-align: end` didn't work (it's not allowed).
---
I added a helper to test RTL layout, but I'm …
> RTL layout fixes

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
This PR fixes an issue on RTL layout with the position of placeholders:
iOS doesn't manage RTL layout automatically on scroll views, so React Native will flip horizontally RCTScrollViews on RTL layout to get the Right to Left effect.
The problem is that we are inserting an view into an already flipped tree of views, and this created all sort of weird layout behavior, braking the `leading` and `trailing` anchored constraints:
```
<RCTCustomScrollView: 0x7f99a3839c00; baseClass = UIScrollView; frame = (0 0; 375 646); transform = [-1, 0, 0, 1, 0, 0]; 
```
Note: `transform = [-1, 0, 0, 1, 0, 0]; `
The solution is a non-conventional horizontal constraint on RTL layout, since `rn-aztec`'s left is logically at the right and right is at the left, but visually they are positioned "correctly.
Since …
> Fix placeholder position for RTL layout

- src/block-management/block-manager.js
- src/block-management/block-picker.js
- src/block-management/block-picker.scss
Fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/349
- Remove the title
- Make column number dynamic
- Update icon/text colors
- Update width/height of icons
- Update Button width/height
- Update justifying to content behavior
Some screenshots to demonstrate portrait/landscape modes for different number of items:
Resepecting Safe Area:
Android:
**TO TEST**
For WPiOS
Checkout the PRs branch to any arbitrary folder and cd .. to it
run yarn install, yarn start
Open XCode WPiOS on the latest develop
Clean build folder on Xcode, and then run the app
For WPAndroid
open grade.properties at WordPress-Android folder
add wp.BUILD_GUTENBERG_FROM_SOURCE = true to grade.properties
checkout the PRs branch in the subrepo of WordPress-Android repo
cd to …
> Improve style of inserter UI

- jest/setup.js
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
- src/block-management/block-manager.js
This PR fixes [wordpress-mobile/WordPress-iOS#10594](https://github.com/wordpress-mobile/WordPress-iOS/issues/10594) for Android. 
Initially we've made a fully JS version of it [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/599), but does't seem to work fine on Android, due to probably the way Android handle the focus. 
I've spent some hrs trying to fix the issue on the Android side (native) without much luck, then added to the bridge the ability to send an event `focus on title` and used it in the android app.
In this PR we wait until the editor is mounted, listen for `editorDidMount`, and emit an event to set the focus on title when both content and title are empty.
**Test 1**
- Use `wp-android`
- Check out this branch and build the app from code
- Start the app
- Tap …
> Fix/Set focus on title for new posts on Android

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Refs #559 
This PR adds a fix to avoid sending invalid caret information that was breaking JS conversion.
> Avoid sending invalid caret rect information.

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
fixes #606 
This PR fixes the dictation content disappearing from Paragraph blocks on iOS.
This is why the issue happens:
1. This happened just on empty TextViews (then explanation will assume that).
2. When the person is dictating, just `textViewDidChange` is called with the new text. (No `insertText`) is called.
3. When dictation finishes, `textViewDidChange` is called first with the text existing previous the dictation (an empty string in this case).
4. RNAztec propagates to the JS side the new content with that empty string.
5. The new text from dictation is inserted and `textViewDidChange` is called again with the full new text. (and RNAztec informs again the JS side)
6. RNAztec receives a `setContents` message from JS from the previous propagation of the empty string. Since JS …
> Fix dictation issue on iOS

- src/block-management/block-manager.js
There is a bridge message in place to let the parent app tell `gutenberg` when it should focus the title. Android seems to be using that mechanism to focus the title.
(Is that correct @daniloercoli ?)
This PR implement the title focus feature using this message from the parent app instead of letting the JS side do it by itself.
The main reason of this change is a glitch on the toolbar + SafeAreas.
Check the WPiOS related PR to see the native side implementation.
**Before:**
**Now:**
**To test:**
- Check out WPAndroid with this branch, and check that the autofocus on new posts still works.
- Checkout the [WPiOS related PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/11097) running **metro on this branch**.
- Check that the autofocus on new posts works properly.
- Check that the …
> Remove JS handling of title focus

- package.json
- yarn.lock
Addresses at least one case of "Pasting from some sources causes a red screen ([related comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/617#pullrequestreview-205427915))" from #624
To test:
0. On the mobile, open the browser and copy the "Gravity Forms" text (it's a link) from https://designsbytierney.com/2010/01/how-to-add-edit-format-text-in-a-wordpress-post-or-page/
1. Run the demo app
2. In a paragraph block, paste
3. It should work and the link be available in the block
> Fix for node.rel crash

- react-native-aztec/android/build.gradle
Just use the Aztec-Android named release as a reference, in preparation of the v1.0 release of gutenberg-mobile. The pointed to code is exactly the same as before, the only changes are in the README file of Aztec.
This change is trivial and I will self-merge to ease with the release process.
> Reference the Aztec-Android tag. Code is still the same

- index.js
- src/app/App.js
- src/app/App.test.js
- src/index.js
Before this, the block titles were not being translated because the translation attempt happened before the locale data was set up.
This refactors the initialization process to ensure we setup localization before Gutenberg is imported
This was originally implemented as part of #643 but that one isn't ready to merge yet
1. Switch your phone/simulator to another language
2. Try to insert a block and verify the title is translated
> Fix i18n initialization priority

- src/variables.android.scss
- src/variables.ios.scss
This PR separates the title padding styles of iOS and Android and removes the vertical paddings of post title on Android because Android handles the paddings on native side.
Changes reside in gutenberg PR https://github.com/WordPress/gutenberg/pull/14057
> Fix title padding on Android

- src/variables.android.scss
- src/variables.ios.scss
Fixes #666 
Currently, each mobile platform has different internal paddings in Aztec so, need to set different block minHeights for each platform.
Gutenberg side PR: https://github.com/WordPress/gutenberg/pull/14070
To test:
1. Run the demo app in both Android and iOS
2. Add a paragraph block. Notice that the block placeholder is fully visible without a glitch.
> Use different block minHeight between the platforms

- src/variables.android.scss
When #664 was merged I wasn't available to properly test but now I saw a small glitch still happening, by following the instructions to test given in https://github.com/wordpress-mobile/WordPress-Android/pull/9324:
> 2. Notice the post title not having this glitch: https://github.com/wordpress-mobile/gutenberg-mobile/issues/666
Currently, the glitch can be seen in [`v1.0.1` tag](https://github.com/wordpress-mobile/gutenberg-mobile/releases/tag/v1.0.1) (for future reference, current commit being pointed by `v1.0.1` is https://github.com/wordpress-mobile/gutenberg-mobile/commit/44f1d996f6a679b9d6197763979eb0b65f7fbea4)
The glitch is hardly noticeable but the solution seemed to go on the right path, so just changing the value a bit made it go away:
So, effectively changed the …
> Fix `min-height-title` to avoid little but still noticeable glitch

- package.json
- react-native-gutenberg-bridge/third-party-podspecs/react-native-keyboard-aware-scroll-view.podspec.json
- yarn.lock
Bumping up react-native-keyboard-aware-scroll-view version on iOS example app.
**To Test**
- yarn install & yarn ios
- check that this fix is included by the test case described there https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/5
> Update react-native-keyboard-aware-scroll-view version on iOS example app

- ios/CustomImageLoader.swift
- ios/gutenberg.xcodeproj/project.pbxproj
- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge-Bridging-Header.h
Refs: #376 
This PR changes the GB bridge class to support the customization of the bridge with extra modules. It also implements on the custom a sample custom image loader, to allow testing of loading of images.
How to test:
- Check that images are being loaded.
> Allow gutenberg bridge to add custom modules.

- i18n-cache/index.js
This PR updates the `i18n-cache` module to fetch the translation files from https://translate.wordpress.org/projects/wp-plugins/gutenberg directly instead of wp.me.
It also adds new languages that seems to be supported.
- Run `yarn clean:i18n-cache`
- Run `yarn i18n-cache`
- Check that no translation is failing to download and that they are all available in `i18n-cache/data`
> Update i18n cache translation urls and new languages

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView.xcodeproj/project.pbxproj
- react-native-aztec/ios/RNTAztecView/HeadingBlockFormatHandler.swift
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-aztec/package.json
This PR updates Aztec to 1.4.4.
Referencing a hash for testing before the formal Aztec release.
I also added a yarn (`update-aztec-ios`) command on `react-native-aztec` to update the dependency easier.
Some changes were necessary to incorporate the Aztec update to Swift 4.2
> Update aztec to 1.4.4

- src/block-management/block-manager.js
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/637
gutenberg PR https://github.com/WordPress/gutenberg/pull/14386
^^^ The issue contains more than 1 issues. 
1. the border makes the text go up/down 1px when it gets and loses focus -> This was already solved with https://github.com/wordpress-mobile/gutenberg-mobile/pull/622
2. When we create a new post the first time block appender's placeholder shows at a slightly different position than the paragraph placeholder so it moves the first time you tap on it. -> This is the problem we are solving in this PR
**Before:**
iOS:
Android:
**After:**
iOS:
Android:
**TEST**
For WPiOS
Checkout the PRs branch to any arbitrary folder and cd .. to it
run yarn install, yarn start
Open XCode WPiOS on the latest develop
Clean build folder …
> Fix block appended placeholder not matching the paragraph placeholder issue

- src/components/html-text-input.js
Fix https://github.com/wordpress-mobile/gutenberg-mobile/issues/428
On iOS there was no way of closing the keyboard on HTML mode, now we are adding keyboardDismissMode option, so user can drag down to close the keyboard. 
Android behavior doesn't change. On Android there's already a keyboard down button. The 'interactive' option is supported for iOS only, so Android will continue having the default value: https://facebook.github.io/react-native/docs/scrollview#keyboarddismissmode
**To Test**
- Run metro on this branch
- Go to WPiOS app
- Open a post and switch to HTML mode
- Tap somewhere to open keyboard
- Verify that drag down closes the keyboard
> Fix - HTML Editor - Keyboard can not be closed

- react-native-aztec/ios/RNTAztecView/HeadingBlockFormatHandler.swift
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/671
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/11258
This PR fixes the issue about heading placeholder not adjusting itself due to heading level.
After the fix:
**To Test**
Checkout branch on WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/11258
- Add heading block
- Change heading level on toolbar
- Verify that placeholder size adjusts accordingly
> [iOS]Update heading placeholder size on heading level change

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
This PR is a second tentative on fixing #707 and uses much of the code introduced in #739 but doesn't relies on `eventCount` , instead it actually checks the previous text if it's empty or not, before wrapping the newly inserted text with default tag.
cc @marecar3 
**To test this PR**
__Test 1__
- Add a new heading block
- The placeholder text should appear
- Start typing in the block
- The styling should be there and the toolbar updated
__Test 2__
- Remove all the text in a Heading block
- The placeholder text should appear again
- Start typing in the block
- The styling should be there and the toolbar updated
__Test 3__
- Add a new heading block
- The placeholder text should appear
- Paste a text in the block
- The styling should be there and the toolbar updated
Make sure to test with …
> 2nd Fix for Placeholder on Heading block

- src/components/html-text-input.js
- src/components/html-text-input.scss
To Fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/744
Root cause analysis and the solution proposal can be found in the issue. ^^^ 
To fix the anomalies we are removing the outer ScrollView and letting the TextView scroll in its own bounds, thus, letting iOS system make the required optimizations.
After the fix:
iOS:
Android:
**Implementation Details**
Since we can not use keyboardDismissMode prop anymore I've added a pan gesture to detect when the user drags down and close the keyboard with it. This is active for iOS only, keyboardDismissMode='interactive' was also an iOS only behavior.
**To Test**
- Open the iOS example app with `yarn ios`
- Switch to html mode
- Verify that text is visible
- Scroll down to the bottom
- Verify that the whole content is visible
- Drag …
> Fix text becoming invisible in HTML editor

- jest/setup.js
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
- src/block-management/block-manager.js
This PR brings in the functionality to:
a) start a Post by sharing an image to WordPress app from the outside, and
b) start a Post by inserting an image to WordPress from the Media section's "upload finished" snackbar.
Please note the bridge and changes on Android were implemented, but this needs an iOS dev to take care of the iOS part.
To test:
Follow the description in the WPAndroid PR https://github.com/wordpress-mobile/WordPress-Android/pull/9442.
**Note:** First make sure to have the `Use Block Editor` setting to `ON` in App Settings. Then:
1. open the Photos app
2. pick a picture and tap the share icon
3. select the WordPress app
4. choose a site and tap on `Add to new post`
5. Observe the Gutenberg editor opens up, with a pre-filled `Image Block` and the selected image starts …
> Start draft with image block

- jest/setup.js
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
- src/block-management/block-manager.js
Reverts wordpress-mobile/gutenberg-mobile#758
as iOS bridge parts still need to be fleshed out.
> Revert "Start draft with image block"

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecArrowKeyMovementMethod.java
The title has it, when we want to override the caret selection (as in the case of deleting a block and coming back to the block above) we should do it _last_ to make sure any other positioning work has finished. Taking into account chained events would be super complex so, adding a delay seems to do the job while easy to understand. This is a try to improve and fix issue A described in https://github.com/wordpress-mobile/gutenberg-mobile/pull/756#issuecomment-474824104, stating here again for clarity:
**Issue A:** After two blocks are merged, a cursor will be placed on the last remembered position in the block. (Affected both iOS and Android platform)
Steps to reproduce:
1. Create a new Gutenberg post with 2 simple paragraph blocks
2. Put the cursor somewhere in the first block except its …
> Added a minimal delay to call setSelection() to enforce special focus handling cases

- ios/gutenberg.xcodeproj/project.pbxproj
- package.json
- yarn.lock
To fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/760
We are updating keyboard-aware-scroll-view reference to fix warning about calling measureSelectionInWindow via UIManager.
**TO TEST**
- run `yarn install`, `yarn start`, `yarn ios`
And then follow the steps on https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/6
> Fix warning about calling measureSelectionInWindow via UIManager

- ios/gutenberg.xcodeproj/project.pbxproj
- package.json
- yarn.lock
To fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/717
Root cause analysis and the fix can be found in child PR:
https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/7
To Test:
Test 1
- Tap on a paragraph or heading block
- Tap link icon on toolbar
- Tap on one of the TextInputs on links ui modal view
- Verify that the background scrollview doesn't scroll automatically
Test 2
- Make a general check to verify old behavior didn't change and we are still able to do autoscroll on text fields that are inside our blocks.
> [iOS]Prevent autoscroll of the main scrollview when we focus on a TextInput on Links UI

- jest/setup.js
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
- src/block-management/block-manager.js
- Reverts wordpress-mobile/gutenberg-mobile#762 (revert of a revert) as I mistakingly merged without having the iOS part ready.
- Original commit history and discussion (changes already tested and approved on Android) in https://github.com/wordpress-mobile/gutenberg-mobile/pull/758
*NEEDS iOS DEV* to implement the bridge parts on that platform.
Copying here for ease of testing and completeness:
==========
This PR brings in the functionality to:
a) start a Post by sharing an image to WordPress app from the outside, and
b) start a Post by inserting an image to WordPress from the Media section's "upload finished" snackbar.
Please note the bridge and changes on Android were implemented, but this needs an iOS dev to take care of the iOS part.
To test:
Follow the description in the WPAndroid PR …
> Start draft with image block (share media to Gutenberg)

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
This PR updates Aztec to 1.5.0
**To Test:**
- Run `yarn install` `yarn start` and `yarn ios` and verify that example app runs successfully.
> Update Aztec to 1.5.0

- src/components/html-text-input-ui/html-text-input-ui-common.scss
- src/components/html-text-input-ui/html-text-input-ui.android.js
- src/components/html-text-input-ui/html-text-input-ui.android.scss
- src/components/html-text-input-ui/html-text-input-ui.ios.js
- src/components/html-text-input-ui/html-text-input-ui.ios.scss
- src/components/html-text-input.js
This PR tries to implement HTMLInputView in a way that more code is shared between platforms, and branching just the necessary parts.
Since there were challenges sharing the HTML TextView that is the main component, and needs a slightly different configuration, the final result is not as strait forward as one would have liked.
Ideally we can check this out, and see if we like it enough to merge.
If this is more complex than it helps, it's all good to not merge and keep `HTMLInputView` as it is.
> HTMLInputView refactor to better share code. 

- package.json
- src/app/AppContainer.js
- src/app/AppContainer.test.js
This PR fixes a problem where the `hasUnsupportedBlocks` sent to the native apps was always `false`.
The reason is that after [this refactor](https://github.com/wordpress-mobile/gutenberg-mobile/commit/e053284e6372afcdac19a7265c034dbed99036e2), the block list is not available on `AppContainer` until the "editor is ready", thus `this.props.blocks` will always be empty on `componentDidMount`.
The solution is to wait for `props.isReady` to be true to check and send `hasUnsupportedBlocks` with the appropriate value.
**Note:** `componentDidUpdate`  is the best place I found to do this check, but sending `hasUnsupportedBlocks` as part of the `editorDidMount` (from `componentDidUpdate`) feels not optimal. I'm open to suggestions (as always). But as a hotfix, it works.
- I'd rename the …
> Fix `hasUnsupportedBlocks` check.

- react-native-gutenberg-bridge/android/build.gradle
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/OkHttpHeaderInterceptor.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
This is the PR based on issue : https://github.com/wordpress-mobile/gutenberg-mobile/issues/376
It allows WPAndroid users who have a private site to access images when creating new blog Post.
Test Steps : 
Follow instructions on WPAndroid related PR : https://github.com/wordpress-mobile/WordPress-Android/pull/9483
> Intercept image request to add access token when site is private

- react-native-aztec/src/AztecView.js
- src/block-management/block-toolbar.js
fixes #702 
This PR fixes an issue that made the Hide-Keyboard toolbar button not work after the Links UI bottom-sheet was dismissed.
Additionally, now on both platform, dismissing the keyboard with this button will clear the block selection.
To test (iOS):
- Select a paragraph block.
- Present the Links UI (pressing the links button on the toolbar).
- Dismiss the Links UI bottom-sheet.
- Press the hide-keyboard button on the toolbar.
- Check that the button works and the keyboard is dismissed.
- Check that the block is now deselected.
To test (Android):
**Note:** On Android, the keyboard is already hidden after dismissing the Links UI.
- Select a paragraph block.
- Press the hide-keyboard button on the toolbar.
- Check that the keyboard is dismissed.
- Check that the block is now …
> [iOS]: Make Hide-Keyboard button work again after dismissing Links UI.

- package.json
- react-native-gutenberg-bridge/third-party-podspecs/React.podspec.json
- react-native-gutenberg-bridge/third-party-podspecs/yoga.podspec.json
- yarn.lock
This PR upgrades react native to the latest version: `0.59.3`.
This last `react-native` patch fixes an issue with running our app in iOS simulator with Xcode 10.2
See this issue https://github.com/facebook/react-native/issues/24139
Note: sourcemap is still broken on Android
> Upgrade react-native to version 0.59.3

- yarn.lock
https://github.com/wordpress-mobile/gutenberg-mobile/pull/676 inadvertently made a very large number of changes to `yarn.lock` (> 2,000 lines added).
We [reverted the PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/803) earlier today because Jitpack builds started to fail.
This PR reverts the large number of changes to `yarn.lock` (I just reverted the changes and ran `yarn`).
You can see that the build now passes on Jitpack [here](https://jitpack.io/com/github/wordpress-mobile/gutenberg-mobile/5883426c05/build.log).
> Revert some changes to yarn.lock

- src/block-management/block-toolbar.js
Part of #476 
This is a simple PR that implements the changes made on https://github.com/WordPress/gutenberg/pull/14697 to improve accessibility on the toolbar buttons.
- Activate VoiceOver: https://github.com/wordpress-mobile/WordPress-iOS/wiki/Using-VoiceOver
- Select the "Add Block" button.
- Check that VoiceOver reads the label, that it reads the element type (button), and it reads the hint (after a couple of seconds).
- Select the "Unod/Redo" buttons.
- Check that it reads the label, the element type (button) and the state (dimmed)
- For some reason it says dimmed instead of disabled, but it's a iOS system thing.
- Select a Paragraph or Heading block.
- Check that the format buttons are read correctly (label and type).
- Activate one of the format buttons (**b**, _i_, ~ABC~, H2, H3, …
> Accessibility Mark I - Toolbar Buttons

- src/index.js
Fixes this warning:
According to the warning, "The controls plugins is now baked-in."
The change was done in https://github.com/WordPress/gutenberg/pull/14634 which was just brought in by merging Gutenberg `master` in #643.
To test:
- Open Gutenberg and verify there are no warnings displayed
> Remove deprecated controls plugin

- react-native-gutenberg-bridge/android/src/debug/AndroidManifest.xml
This PR supersedes https://github.com/wordpress-mobile/WordPress-Android/pull/9510 as per @hypest suggestion to have any RN-related code contained in the bridge 👍 🙇 
This PR adds React Native's `DevSettingsActivity` to the `debug` manifest for accessing debugging settings while debugging WPAndroid+Gutenberg integration
To test (using WPAndroid):
1. build `ZalphaDebug` or for the case, any debug flavor
2. make sure to have Gutenberg enabled in App Settings (use Block Editor for new posts)
3. start a new draft to launch GB
4. tap on the overflow menu icon, then Debug Menu
5. in the RN's debug menu, select `Dev Settings`.
6. observe the app doesn't crash
> Added manifest merge to enable use of React Native's DevSettings screen

- .circleci/config.yml
Updating the CircleCI image to use API 28 seems to remove the need to accept licenses 😄
> CircleCI: Use API 28 for Android build

- src/block-management/block-holder.js
This PR does help on mitigating the problem reported in #311, where under some circumstances the caret is moved to another block when the current `TextInput` powered block in moved down by the user. The problem was originally reported for Android, but it seems could happen on iOS too, even though with less frequency. 
In this PR we're just hiding the Keyboard on block Up/Down/Delete operations.
**A GIF of the original problem**
During my tentative to fix the problem I've also found other scenarios where the same issue comes up on writing. 
IE:
- Tap on a para block (that's not the first one on the list)
- Tap on the Page break block
- Boom 🤯 the caret is moved to the first TextInput block in the list
For more details see the comment and video linked here …
> Mitigate the problem of moving the current block down sets the caret to the wrong block 

- package.json
- yarn.lock
The [recent upgrade to React Native 0.59](https://github.com/wordpress-mobile/gutenberg-mobile/pull/741) had a regression that made us lose the ability to properly debug the JS source code under Android.
This PR introduces a workaround by using the fixes version of the `react-native-cli` package, before it becomes available directly via a future React Native release.
Relevant tickets: https://github.com/facebook/react-native/issues/23955, https://github.com/facebook/metro/issues/380
To test:
0. Add a `debugger;` statement somewhere in the JS code. Good examples can be the `block-holder.js` module and the `render()` function in `gutenberg/.../components/rich-text/index.native.js`.
1. Run the demo app on Android
2. Enable the Remote JS debugging mode via the debug menu, and notice Chrome …
> Use react-native-cli with the Android debugging fix

- src/globals.js
- src/jsdom-patches.js
This PR aims to address (and clarify) the functions added to the `jsdom-patches.js` file, imported in `globals.js`. No code is modified by these commits (only comments).
Please let me know if any further clarifications would be useful.
> Add comments to clarify functions in jsdom-patches file.

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
This PR fixes #856 by making sure to check if text listeners are enabled before doing any text/block manipulating action `onEnter` or `onBackSpace`. 
In this particular case the BackSpace.Key detection code in Aztec is called when the initial empty HTML content is set to the block via `setTextFromJS`. Text listeners are disabled in this case, and those are not running, but InputFilters are not disabled.... By the way, I guess a better fix would involve changes to Aztec, but probably is easier to fix them here, since this change could also fix other potential problems in the future.
Steps to repro:
- Start the demo app on STOCK emulator (Check AOSP keyboard)
- Insert a new empty para block
- Make sure it stays on the screen
> FIX empty block creation on device running AOSP keyboard

- android/app/src/main/java/com/gutenberg/MainApplication.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
This is done to match the iOS counterpart implemented in https://github.com/wordpress-mobile/gutenberg-mobile/pull/810
This PR only adds the methods and wiring, but the implementation doesn't actually do anything, as I don't think we need to do anything in particular on the Android side.
I tried copying an image from Google photos and it just doesn't seem to offer such an option - it's all done through the `share` icon that is done (and we are already handling that).
Also, if you try and copy images and/or text from the web on a browser, the `img` tag with the link gets copied in the buffer, and pasting works  "automagically" with the Gutenberg code making it an `Image` block, so, it seems to me we don't need extra code to handle this.
> Add `requestMediaImport` method to the Android bridge

- react-native-aztec/android/build.gradle
Fixes #845 
This PR updates to a fixed Aztec Android version. No changes on the gutenberg-mobile side.
Aztec-Android PR: https://github.com/wordpress-mobile/AztecEditor-Android/pull/807
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/9614
To test:
1. In the demo app, do a long list, long enough to have a few empty list items here and there
2. Try to add a new item at the end of the list
3. The new list item should be normally created at the end and the caret should be placed on it
> Use the Aztec-Android version with the #845 fix

- .circleci/config.yml
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
This breaks compatibility with Xcode versions < 10.2 so merging should be done carefully. The only change is an update to Aztec-iOS (see https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1172).
> Xcode 10.2 compatibility

- android/app/src/main/java/com/gutenberg/MainApplication.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
https://github.com/wordpress-mobile/gutenberg-mobile/pull/876 has been merged but @mzorz spotted an issue that we want to include a fix for.
The only change here is cherry-picking the fix for https://github.com/wordpress-mobile/gutenberg-mobile/pull/864 onto the release branch.
JS bundles are not updated since there is no JS change.
> Release/1.2.1 - Take two

- package.json
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes a part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/888
Related Aztec PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1175
This PR removes the Tab and Shift+Tab key shortcuts.
On a second iteration of the ListBlock, we will want to reactivate them using gutenberg internal mechanism.
I also removed the `Tab` key functionality completely. It was adding tab characters to the content of blocks, and also breaking the ListBlock. This is different to how it works on Android and Web, so I don't see any harm on deactivating it until we handle it properly (cc @hypest )
IMHO, the functionality we want for the Tab key in this case is to move the focus to the next block, in the same way it works on web.
To test Tabs:
- Run the iOS example project on the simulator. …
> [iOS] Deactivate Tab and Shift+Tab key shortcuts

- __device-tests__/helpers/utils.js
This PR updates the tests to provide a URL to access the video recording at the end of test execution in CI(or locally if running on SauceLabs). SauceLabs docs for building the URL can be found [here](https://wiki.saucelabs.com/display/DOCS/Building+Links+to+Test+Results) In CI at the end of the test run, the following should be printed 
`You can view the video of this test run at ${ jobURL }`
> log jobURL at end of successful job

- src/block-management/inline-toolbar/index.js
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/911
**To test (iOS):**
Activate VoiceOver: https://github.com/wordpress-mobile/WordPress-iOS/wiki/Using-VoiceOver
**To test (Android):**
Activate TalkBack: https://www.wikihow.com/Enable-TalkBack-on-Your-Android
In my case, the system had a handy tutorial on how to use it.
If your version doesn't have it, it's actually very similar to VoiceOver.
**Test Steps**
> Improve Screen Reader support for Inner Toolbar

- react-native-aztec/android/build.gradle
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecBackSpaceEvent.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecEnterEvent.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
- react-native-aztec/android/src/main/kotlin/org/wordpress/mobile/ReactNativeAztec/EnterPressedWatcher.kt
- react-native-aztec/src/AztecView.js
Fixes #898 , #899 
Gutenberg: https://github.com/WordPress/gutenberg/pull/15168
Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull/812
This PR updates the way the "Enter" key is processed along with the general way changes from Aztec (Android) are updating the RN state without forcing them back to Aztec again.
This PR is WIP.
An Aztec-Android, the virtual keyboard has different behavior than external/hardware keyboards and the program flows through different code paths depending on whether it's the virtual keyboard or not. The key press from hardware keyboards is detected/intercepted before it changes the editor's text, the opposite happens on the virtual one. On the hardware keyboard, the event can be intercepted (and swallowed) upon detection, while on the …
> Fix List block handling on Android

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-aztec/src/AztecView.js
fixes #843 
Maybe this one too: https://github.com/wordpress-mobile/WordPress-iOS/issues/11583
This PR fixes an issue where the editor enters on a onFocus/onBlur infinite loop. This was easily reproduced by selecting text on a paragraph block, and moving it inside the same block.
I tracked the issue until this line:
https://github.com/wordpress-mobile/gutenberg-mobile/blob/6513ba88076009b883f8b708ec48dfcbe92793b5/react-native-aztec/src/AztecView.js#L149
But we need it in order to let Gutenberg know that the TextView was focused by iOS. Needed to solve this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/702
With some investigation I noticed that `textViewDidBeginEditing` was sending one extra `onFocus` event that is not needed, and that triggered the loop. It was solved …
> Fix move selected text on iOS

- README.md
This PR adds simple instructions to the README doc for running the iOS simulator with other devices.
> Add instructions for running simulator with other iOS devices to README

- .flowconfig
- bin/ci-checks-js.sh
Recently there have been a significant number of both jest and flow failures on CircleCI. This limits parallelization of both so that memory problems are avoided.
I have run this many times already, and it seems to be working reliably (see [here](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/tree/circleci-memory-issues)).
Related to https://github.com/facebook/flow/issues/6242
> CircleCI: Limit max Jest and Flow workers to avoid memory errors

- react-native-gutenberg-bridge/android/build.gradle
Fixes : https://github.com/wordpress-mobile/gutenberg-mobile/issues/904
At the time when I was working on this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/788/files, for some reason, I trusted Android Studio IDE when it was complaining about missing classes from imagepipeline-okhttp3 dependency, so I have included dependency.
After some time I have found out that I was wrong and that I mistakenly put dependency which was already part of RN core: https://github.com/facebook/react-native/blob/758eb9fa7bba1d1a14fd8c8870e2a00ad3a31809/ReactAndroid/build.gradle#L316
Test : 
Compile RN `react-native-gutenberg-bridge` with command : `./gradlew clean assembleDebug`
> Remove duplicated imagepipeline-okhttp3 dependency

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
This PR adds a `textAlign` property to the `ReactAztecManager` so the text in image captions can be centered. See the [companion gutenberg PR](https://github.com/WordPress/gutenberg/pull/15257) for usage on the React Native side.
This addresses the loss of center alignment for image captions that was introduced when [the image caption was switched to use a `RichText` component](https://github.com/WordPress/gutenberg/pull/14883).
⚠️ Implementation of the `textAlign` prop still needs to be completed on iOS.
1. An image caption's text should have center alignment when the image caption is not selected.
2. An image caption's text should have center alignment when the image caption is selected.
3. An image caption's text should have center alignment when the image caption is being edited.
4. …
> Add text alignment prop for centering image captions

- package.json
This PR updates the Gutenberg reference to bring in the changes in this companion PR: https://github.com/WordPress/gutenberg/pull/15532.
This PR adds a check to ensure `attributes.url` exists before attempting to call `indexof`. Currently, there are scenarios which can result in `attributes.id` being truthy, while `attributes.url` is null or undefined for an image block.
When an image is cancelled before it is finished uploading, the `url` is set to `null`, but the `id` of the block remains. The next time the post is edited, the local draft will contain the state which triggers the crash.
This was tested using the steps here: https://github.com/wordpress-mobile/WordPress-Android/issues/9768#issuecomment-490852531
This is a bug fix for the crash discovered here: …
> Fix crash on undefined image url

- package.json
**Note:** This PR targets a new release branch `v1.3.1` created from the gutenberg-mobile tag `v1.3.0`, which is used in WordPress-Android `v12.3.1`.
This PR updates the Gutenberg reference to bring in the changes in this companion PR: https://github.com/WordPress/gutenberg/pull/15618.
This PR adds a check to ensure `attributes.url` exists before attempting to call `indexof`. Currently, there are scenarios which can result in `attributes.id` being truthy, while `attributes.url` is null or undefined for an image block.
When an image is cancelled before it is finished uploading, the `url` is set to `null`, but the `id` of the block remains. The next time the post is edited, the local draft will contain the state which triggers the crash.
This was tested using the steps here: …
> Hotfix - v1.3.1 - Fix crash on undefined image url

- react-native-aztec/android/build.gradle
We are already using the changes AztecAndroid v1.3.27 introduces (used here https://github.com/wordpress-mobile/gutenberg-mobile/pull/949) and this PR just updates the pointer to use a release tag.
This is a trivial, release process related PR so, will self-merge as soon as CI turns green.
> Use AztecAndroid's v1.3.27 tag

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
This brings the demo app dependency on Aztec to the latest release
List of changes: https://github.com/wordpress-mobile/AztecEditor-iOS/compare/1.6.1...1.6.3
> Update Aztec-iOS to 1.6.3 in the demo app

- src/block-management/block-picker.js
This crash occurs when we we try to show block picker. It is not yet on the develop branch but it will come in when we update the gutenberg ref to the latest master. This looks like a side effect of: https://github.com/WordPress/gutenberg/pull/15462/files
To test:
- Tap on (+) and display the block picker
- Verify it doesn't crash
- Verify Heading block has a new icon
> Fix crash occurring when we try to display block picker

- android/app/src/main/java/com/gutenberg/MainApplication.java
Fixes #1015 
To test:
Run the demo app on Android. It should normally load without a red screen.
> Re-load the ReactVideoPackage that got removed by #821

- __device-tests__/gutenberg-editor-lists-end.test.js
- __device-tests__/gutenberg-editor-lists.test.js
- __device-tests__/helpers/test-data.js
- __device-tests__/pages/editor-page.js
This PR adds an Appium test for testing the list block ending when inputting an "Enter" at an empty list item where the expectation is that that block should "end" and a new empty paragraph should be created underneath it.
1. The test only really tests the Android side of things as on the iOS we're still missing an implementation of the html check step. See https://github.com/wordpress-mobile/gutenberg-mobile/blob/876ebe714219f4f0ba3ab23e82e535747db041e6/__device-tests__/pages/editor-page.js#L272-L278
2. The new test is added in a _new_ testsuite module (a file separate to the other list test module) because we currently don't have a good way to clean up the state and blocks before starting the next test case. With a separate testsuite, the whole editor is cleaned up by tearing it down …
> List end test

- src/block-management/block-holder.js
Fixes #1023 
This PR updates the `onReplace` dispatcher call to pass `indexToSelect` to it.
Relevant change on the web side:
https://github.com/wordpress/gutenberg/commit/eddd4fcd30f6a4ac8ce221888a8bcde397158476#diff-86ce6d1930888d88a252e7d2ee38334aR712 from the [RichText: stabilize onSplit](https://github.com/WordPress/gutenberg/pull/14765) PR.
To test:
1. Place the caret at the end of a middle item on the list of the demo content
2. Tap an "Enter" to create a new list item
3. Tap "Enter" again to split the list
4. A new paragraph block should be created in-between the split list and the caret placed in it
> Follow web side's lead to add `indexToSelect` to onReplace

- __device-tests__/helpers/caps.js
Updates default platform version and appium version used in CI
To test:
Checking that the tests pass in CI is enough. 
> Update default versions used in CI

- RELEASE-NOTES.txt
- src/block-management/block-holder.js
Fixes #969 
This PR implements `BlockInvalidWarning` on `BlockHolder` to show a warning UI when the block content is invalid.
`gutenberg` side PR: https://github.com/WordPress/gutenberg/pull/15789
To test:
- Run the example app.
- Display on gutenberg the HTML content from [here](https://gist.github.com/etoledom/a47cfe010a0f5c9f410d5c226b1560b3)
- You will see a red screen (since there is invalid content).
- Dismiss the red screen.
- Check that the invalid content UI is showing for all blocks. 
> UI for invalid block content

- RELEASE-NOTES.txt
This PR updates the gutenberg ref to test https://github.com/WordPress/gutenberg/pull/15812
It fixes the "Open in New Tab" option for links in gutenberg-mobile, where the switch started always off, even a link target was set.
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1018
**To test:**
Please refer to https://github.com/WordPress/gutenberg/pull/15812 for testing steps.
> Fix link "open in new tab" switch

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
Fixes #938 
This updates the current version of Aztec to 1.6.5. 
The main benefit of this version is to get copy/paste working across text blocks and copy/paste to external apps.
To test:
- Start the demo app in iOS
- Copy a bit of text from one block
- Paste it on another block
- Paste to another app in the system ( Notes app or Reminders)
- See if the plain text is copied.
> Update Aztec version to 1.6.5

- __device-tests__/gutenberg-editor-lists-end.test.js
- __device-tests__/gutenberg-editor-lists.test.js
- __device-tests__/gutenberg-editor.test.js
- package.json
This PR adds code to focus on blocks before sending text to them on Android. In some cases, if this wasn't done the text would be sent to the wrong block. 
To test:
* Ensure all tests pass locally and in CI 
> Focus blocks on Android Device Tests

- package.json
- yarn.lock
This PR is a quick fix for wordpress-mobile/WordPress-Android#9943 
Makes sure to not set background color on Android.
To test:
See details WordPress/gutenberg#15857
[ x ] If there are user facing changes, I have added an item to RELEASE-NOTES.txt.
> Fix for video block crash on drawing on Android

- src/block-management/block-manager.js
Fixes #1042 
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/15878
This PR adjusts the logic to be closer to the web's side of how/when a block gets selected when newly created.
It contains two changes:
1. When a block gets created from the Inserter, we now let the global selection logic to take over trying to focus the new block, based on the updated selection state (wrangled on the web side). cd47572 has that change.
2. Resolve the race condition where `RichText`s in blocks with multiple RichText components would compete in getting the focus. On the web, the equivalent to our BlockHolder actively tries to focus one of the inputboxes (see [here]( https://github.com/WordPress/gutenberg/blob/cb127c93baa22222d9c31eac8ea25efec8ac6cba/packages/block-editor/src/components/block-list/b …
> Focus the right RichText

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
Fixes #1044 
This PR simply updates the Aztec reference in order to have support for copy/cut paste of HTML in the editor
To test:
- Copy paste text from one block that has formatting active: for example bold italic
- Paste it to another block
- See if formatting went across
- Copy a list element
- Paste it in a new block
- Copy a heading
- Paste it to a new block.
> Update Aztec reference.

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/OkHttpHeaderInterceptor.java
This PR fixes https://github.com/wordpress-mobile/WordPress-Android/issues/9833 by making sure the Auth header requested listener is not null before using it. As described in this comment [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1056#issuecomment-498183372) the auth header requested listener is unset on exit of the editor, but the network queue is still filled with "old" pictures request. When the queue process those pictures the listener previously unset is invoked leading to the crash.
To test:
- Load a post with lot of pictures
- Exit the editor asap
- Wait until all the request end and no crash
- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.
> FIX NPE in WPAndroidGlue while setting Auth header

- RELEASE-NOTES.txt
- react-native-aztec/src/AztecView.js
fixes #1063 
fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/11583
The issue happens when the blur event takes longer to get to the native side than the second Enter. When this happens, a second onEnter -> onSplit chain of events is fired while the first one is still occurring. This seems to be confusing for the gutenberg store.
This doesn't happen on Android because of this:
https://github.com/wordpress-mobile/gutenberg-mobile/blob/ec43c9f1f4709fccdb9d5c74bd6681ae4e621b76/react-native-aztec/src/AztecView.js#L153-L155
On Android the focus-blur loop is broken there, but on iOS this is needed to solve this issue https://github.com/wordpress-mobile/gutenberg-mobile/pull/784
To test:
- Run the example project from develop on the oldest/slowest device available
- Try to …
> Avoid sending onEnter when AztecView is not focused.

- package.json
- symlinked-packages/@wordpress/server-side-render
- yarn.lock
Fixes:  Failing unittests
Error:
https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/6711?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Seems to be related with the following commit: https://github.com/WordPress/gutenberg/commit/01db6008fdf7b4c4e77647bb31dac8ca94a12704
To test:
Wait for the CI get green
> Fix failing unit tests because of the new package `server-side-render`

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #207
Relate GB PR: https://github.com/WordPress/gutenberg/pull/16013
This PR fixes the following issues around the insertion and removal of empty lines inside quotes:
- It was impossible to insert multiple empty lines inside a quote block
- After the insertion of an empty line at the end of the quote block, trying to remove it caused a crash or the merge of the block with the block above.
The main changes are the following:
-  Aztec is updated in order that empty block elements are not removed. So when entering a new line in quote that results in this HTML: `<p></p>` isn't remove by Aztec
- Checks are done in GB JS code to check if the selection range returned by iOS is inside the text length in the format structure. This could happen in scenarios where extra characters were added …
> Quotes: Fix handling of insertion and removal of empty lines.

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1064 
This PR removes the system drag and drop text functionality from Aztec-iOS Wrapper.
The focus loop issue could be fixed by not sending selection change events to JS when Aztec is not firstResponder, but there is also another issue: After dropping text to a new block, it looses all its formatting.
With @SergioEstevao we decided that is best to remove this functionality until we manage to fix this other issue too.
To test:
- Select a couple of lines of text on a paragraph block.
- Long press over the selection.
- Check that nothing happens.
> Remove drag-drop text interaction from Aztec-iOS wrapper

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #
This PR fixes an issue where selecting a range of text on a block and pressing delete was not working properly.
To test:
- Open the demo app
- Select a range of text in any block
- Press delete
- Make sure the text is deleted.
- Just to make sure all is correct, also text pressing delete with when no range selection is done.
> Do not intercept delete when there is a range selection.

- src/jsdom-patches.js
Fixes #827 
This PR aims to fix an issue on mobile (https://github.com/wordpress-mobile/gutenberg-mobile/issues/827) where pasted content from certain sources omits the images. Related comment: https://github.com/wordpress-mobile/gutenberg-mobile/pull/617#pullrequestreview-205427915, and a clipboard snippet of html that reproduces the issue on mobile here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/827#issuecomment-483913821.
1. Select content from [this site](https://designsbytierney.com/2010/01/how-to-add-edit-format-text-in-a-wordpress-post-or-page/), including text above and below the image above "The Visual Editor.". Alternatively, if you are using an emulator with shared clipboard, it suffices to copy the html from the snippet referenced above.
2. Create an empty …
> Implement jsdom node traversal properties

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextShadowNode.java
Addresses #1091
This PR implements the shadow node logic for the Aztec wrapper custom React Native view. This is needed for better View calculations.
This work begun as an attempt to remove the need to specify the `minHeight` style  on the Aztec wrapper. I think that the view should be able to update its height automatically within RN and the Android layout system, without us manually having to set it as a style prop. In that respect, the effort here is not finished; the `minHeight` style is still needed (try removing it and you'll see that the wrapper doesn't update its height properly, although its now initial height is much better than before). Although, my experiments so far with a basic demo app (in repo: https://github.com/hypest/RN060-aztec-experiments) seem to work and the Aztec …
> Implement the shadow node for proper laying out Aztec on Android

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
This PR does implement the Android side of the PR here #1086 by making an hardcode reference to the default GB link color. 
As agreed in Slack conversation, this is a required hack for Android until we find a better solution that works fine on all devices without requiring a repaint of the screen. Ref: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1106 and https://github.com/wordpress-mobile/gutenberg-mobile/pull/1101
Follow testing steps here: #1086 (comment).
- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.
> Hardcode link text color in Android

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
This PR improves the copy paste of lists inside GB mobile by replacing paragraph separators for line feeds.
This allows the paste code in GB to recognize the lists better when pasting inside another block.
To test:
- Copy a list block by doing select all copy on it
- Paste the resulting code inside another text block.
- See that a list block is created.
> Improve copy paste of lists

- bin/update-bintray-repo.sh
Fixes #1114 
To test:
Try running `./bin/update-bintray-repo.sh` to publish to Bintray, and it should work by reporting that the versions on the mirror are already there.
> Copy i18n-cache folder too on publishing to Bintray

- package.json
This PR fixes wordpress-mobile/gutenberg-mobile#1092 by making sure the selection is valid before calling the update on the native layer (Aztec Wrapper).
To test:
- Paste multiline content into the title
- Paste single line content into the title
- Write something in the title and repeat steps above
GB side: https://github.com/WordPress/gutenberg/pull/16037
Please, remember to update the hash after the merging GB side.
- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.
> Fix v1.6.0 crash when pasting on the Title Block

- __device-tests__/gutenberg-editor-paragraph.test.js
- __device-tests__/gutenberg-editor-rotatation.test.js
- __device-tests__/helpers/test-data.js
Fixes failing device rotation tests on develop
To test: device rotation tests should pass both locally and on CI
> Fix device rotation tests

- src/block-management/block-holder.js
- src/block-management/block-manager.js
Fixes #1126 
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/16151
To test:
1. Remove all the content
2. Insert an image
3. Remove the image
4. Ensure there's no crash
> Narrow blur on unmount to replaceable

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #954
This PR addresses the issues iOS were empty lines are being added to new lists or quotes blocks.
It also fixes the placeholders visibility  and style on both blocks.
To test:
- Add a new list block
- Check if placeholder info code shows up.
- Edit the list and add new list elements and check that no new empty line shows up in the end
- Split lists
- Indent and outdent
- Add new quote block
- Check that placeholder text shows up
- Edit the quote and check that no extra empty lines show up when editing
> Removes empty lines lists and quotes

- src/app/initial-html.js
Fixes the following errors happening since the Heading block was updated in https://github.com/WordPress/gutenberg/pull/16035
```
Block validation: Block validation failed for `core/heading` ({name: "core/heading", save: ƒ, category: "common", attributes: {…}, title: "Heading", …}).
Content generated by `save` function:
<h2 class="has-text-align-left">Meet your new best friends, Blocks</h2>
Content retrieved from post body:
<h2 style="text-align:left">Meet your new best friends, Blocks</h2>
```
To test:
Boot the app locally and check that the block validation errors are no more.
> Manually migrate heading block to the new syntax to avoid block validation errors

- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
This PR introduces a way to modify the level of logging. It also modifies the default log level threshold to `trace` if the packager is running (as it was before), and to `error` otherwise (the default for release builds). This help non-gutenberg devs to avoid the gutenberg verbose logs when they interact with the block editor.
**Note:** The sockets error messages are not managed by this PR :( 
To test:
- Launch the demo app from Xcode (ios/gutenberg.xcodeproj) with metro running.
- Check that you see the `Running application gutenberg` logs
- There is one from JS side sent through the bridge and one directly from the native side.
- Check that you see some warnings when the content appears.
- Rebuild and lunch the app again.
- Stop the metro server while the app is building.
- Check that …
> Reduce iOS bridge logging

- .circleci/config.yml
This makes some small improvements to how we cache `yarn install` on CircleCI. I spotted it was slow even when cached when working on some other things earlier.
The improvement is modest but it adds up. Prior to this, restoring the cache and running `yarn install` took 40 seconds for `Check Correctness` and 80 seconds for `Test iOS on Device`. It now takes 20 and 40 seconds respectively.
This is what I changed:
- We now cache `i18n-cache/data` do it doesn't need to download each time.
- Cache `node_modules/` instead of `~/.cache/yarn`. Most of the time was spent copying files over from here.
- Add `--prefer-offline` to get the best speed we can.
- Use a separate cache for each job. It seems the images each create a slightly different `node_modules/`.
To test:
CI passes 😄 
Update release …
> CircleCI: Better yarn caching

- .circleci/config.yml
This reduces the typical time to run iOS device tests on a PR from ~17 minutes to ~9 minutes. It does this by caching `gutenberg.app` and skipping the compiling steps if no native iOS code has changed.
To test:
- See that the device tests ran correctly on this PR.
> CircleCI: Speed up iOS device tests by caching gutenberg.app

- src/globals.js
This PR solves a crash updating the gutenberg ref to master.
The crashing code was introduced here:  https://github.com/WordPress/gutenberg/pull/16065/files
This line in particular: https://github.com/WordPress/gutenberg/blob/3279e116b9486099a681282a7aae050c96f563c6/packages/compose/src/hooks/use-reduced-motion/index.js#L11
The crash:
This PR also brings the gutenberg ref up to date with gutenberg master.
**To test:**
- Try to reproduce the error:
- Check out develop
- Update the gutenberg ref to master
- A red screen should appear
- Check out this branch
- Run the app.
- Check that it doesn't crash.
> Adding `navigator.userAgent` to our globals to solve a crash

- RELEASE-NOTES.txt
This PR introduces tappable empty editor area which creates a new paragraph block.
It's the first iteration of https://github.com/wordpress-mobile/gutenberg-mobile/issues/358 intended for the Beta release. 
Next iteration would cover more complex UI: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1020
Following gutenberg PR: https://github.com/WordPress/gutenberg/pull/16439
To test: 
1. Open the Gutenberg Editor
2. Tap on the empty editor area
Result: New paragraph block should be created
> Tapping on an empty editor area creates a new paragraph block

- RELEASE-NOTES.txt
- android/app/src/main/java/com/gutenberg/MainApplication.java
- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
This PR fixes #1174 by receiving the list of unsupported blocks from GB when opening a post. 
Basically this PR updates the native bridge and the Android glue code to deal with the changes made in GB. Previously GB was only sending a flag to the bridge, to notify the presence or not of unsupported blocks.
GB side PR: https://github.com/WordPress/gutenberg/pull/16434
I will update `wp-android` and bump the analytics accordingly to the new signature when this PR  is merged. 
To test:
- Open the demo post in the demo app
- Put a breakpoint [here](https://github.com/wordpress-mobile/gutenberg-mobile/compare/issue/1174-track-unsupported-blocks?expand=1#diff-790122ff7222773fbfe709696f8eedc5R73) and check the the array of unsupported block is correct
- [ x ] If there are …
> Track unsupported blocks

- package.json
- react-native-gutenberg-bridge/third-party-podspecs/RNSVG.podspec.json
- yarn.lock
This updates the `react-native-svg` hash to include the fix from https://github.com/wordpress-mobile/react-native-svg/pull/5 (should be merged first). It ensures `pod install` doesn't use an old, cached version of `9.3.3`.
> Update react-native-svg version

- RELEASE-NOTES.txt
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1206
Gutenberg side PR: https://github.com/WordPress/gutenberg/pull/14443
To test:
- Boot the demo app with the following value in `initial-html.js`
```
<div class="wp-block-group"><div class="wp-block-group__inner-container">
<p>hello world</p>
</div></div>
```
- switch to html and notice the value is preserved.
- Try the repro step on https://github.com/wordpress-mobile/gutenberg-mobile/issues/1206 on WPiOS and WPAndroid to make sure no content is loss.
> Fix content loss in Group block

- __device-tests__/gutenberg-editor-rotatation.test.js
- __device-tests__/helpers/utils.js
This PR patches 2 things on Android
1. when running the Copy/Paste test locally, the click of `Select all` can sometimes accidentally touch the element before the next context menu appears. 
2. When running the device test locally, it could fail to find the paragraph block while the keyboard is being hidden
Tested on: Pixel and Pixel 2 XL emulators and on Pixel 3a physical device
To test: Run the full e2e test suite locally, they should pass 
> Fixed flaky issues with Android device tests

- RELEASE-NOTES.txt
This PR updates the behavior when inserting a block which the post's title is selected. Previously, the block would be inserted at the bottom of the post, but now it will be inserted at the top of the post. This work is being done in advance of addressing #632 (missing "Add New Block" indicator when inserting a block from the post's title) so that we're inserting the post at the proper location before we add an "Add New Block" indicator for the insertion position.
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16440)
Before | After
---- | ----
1. Load demo app
2. Tap on the post Title to select it
3. Add any block
4. Observe that the newly added block is inserted at the **top** of the post
1. Load demo app
2. Do **NOT** select any block
3. Add any block
4. Observe that …
> Insert blocks at top of post when post title is selected

- RELEASE-NOTES.txt
Fixes #632 : "Add Block Here" (ABH) indicator isn't shown when title field is focused.
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16539)
Before | After
----- | -----
The ABH indicator is still not shown when a new post is created and a new block is added _before_ the user has interacted with the post content (i.e. if the user either tries to add a block first thing or only interacts with the post title, then adding a new block will not display the ABH indicator). This is because the ABH indicator is attached to our block holders, but until the user taps on the "Start writing..." placeholder text in a new post, the post does not actually contain any blocks (it just has a `RichText` field that is replaced with a block `onTouch`). This actually may not be a bad thing …
> Show "add block here" placeholder when adding block from title

- RELEASE-NOTES.txt
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16642)
Fixes #932 , which was the problem that any time the post title was selected and a new image block was added, the post title would retain focus (i.e., the cursor). In fact, this issue occurred anytime a non-text block is added from the `post-title`. In particular, adding `image`, `video`, `more`, `seperator`, or `page break` blocks all leave focus with the post's title if it had focus immediately before the new block was added.
Before | After
---- | ----
This PR insures the post-title is not selected when a new block is created by updating the post title to not be selected any time there is a selected block in the redux store (the post's title itself is not considered a selected block).
An alternative approach would …
> Blur post title any time a new block is added

- RELEASE-NOTES.txt
Fixes an issue where inserting a block from the post title would not replace an empty paragraph block if that block was the first block in the post. Instead it would add a second empty paragraph block at the beginning of the post.
See [related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16574) for further detail and testing instructions
~~I did not update the release notes because this seemed like a minor fix for an issue that was just introduced in 1.9, and which very few users would ever encounter. Just let me know if anyone thinks this should go in the release notes.~~
Release notes updated.
> When inserting block from title replace block if appropriate

- .vscode/extensions.json
Update vscode extension config to prevent VSCode to show a warning on project opening.
I noticed this warning in VSCode:
In version 0.9.3, they changed extension publisher from `vsmobile` to `msjsdiag`, see release notes there: https://github.com/microsoft/vscode-react-native/blob/master/CHANGELOG.md#093
> Update vscode extension config to prevent VSCode to show a warning on project opening

- README.md
Node 9.x doesn't really seem relevant anymore since we are now directing devs to setup with `nvm install --latest-npm` (currently v.12.6.0), so I thought we might as well remove these lines in order to avoid any possible confusion. I think they're just a remnant from when the project needed node 8.x instead of 9.x. 
Just let me know if you think there's any reason we should keep this in here.
To test: N/A
Update release notes: N/A
> Remove references to node 9 errors in readme

- __device-tests__/gutenberg-editor-block-insertion.test.js
- __device-tests__/helpers/utils.js
- __device-tests__/pages/editor-page.js
Test PR for https://github.com/WordPress/gutenberg/pull/16677 (merged)
Now test PR for https://github.com/WordPress/gutenberg/pull/16906
> Refactor BlockToolbar out of BlockList 

- package.json
- react-native-aztec/android/build.gradle
**Summary:**
While working on Chromebook issues we have made some fixes on https://github.com/wordpress-mobile/AztecEditor-Android repository and before we tag `v1.3.29`, we need to make sure that nothing has broken on Gutenberg level.
Main AztecEditor PR that bumps version to `v1.3.29`: https://github.com/wordpress-mobile/AztecEditor-Android/pull/841
PR's that were resolved: 
- https://github.com/wordpress-mobile/AztecEditor-Android/pull/840
- https://github.com/wordpress-mobile/AztecEditor-Android/pull/838
- https://github.com/wordpress-mobile/AztecEditor-Android/pull/835
**To test:**
We should test Block Editor in general so that we can be sure that above PR's didn't expose any regression.
> Hotfix - 1.10.1 - Update to android aztec v1.3.29

- react-native-gutenberg-bridge/ios/Gutenberg.swift
Fixes #1190 
This PR fixes an issue on WPiOS that crashes the app when trying to start a photo post from the 3D Touch shortcuts.
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12286
To test:
- On WPiOS, check out https://github.com/wordpress-mobile/WordPress-iOS/pull/12286
- Build and run on a iOS **device with 3D touch** (iPhone 6S family or later)
- When the app is running, send it to background
- Find the WordPress app icon, and "force touch" it to display the shortcut options.
- Select "New Photo Post"
- Choose an image (or a few)
- Press on "Insert" at the bottom right corner
- Check that the images are added to the post and there is no crash
> Bridge iOS: Add mediaType to appendMedia event.

- RELEASE-NOTES.txt
Fixes #934 by resetting the toolbar's scroll position any time it's content changes. Additional information and test steps are available in the [related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16945).
Release notes have been updated.
> Reset toolbar scroll on change

- react-native-aztec/android/build.gradle
This PR updates the Aztec version used in the Aztec wrapper for Android.
Changes made to Aztec are minimal, and added a couple of methods to keep track of toolbar button pressed, and undo/redo events.  https://github.com/wordpress-mobile/AztecEditor-Android/pull/843
**Note**: Undo/Redo buttons live outside Aztec at the moment of this PR, so we could track tapping on those directly in the host apps, but we've agree to consider those buttons as they were part of the aztec-editor toolbar. We wanted to be "location" agnostic and be ready to move the undo/redo into the toolbar quickly if necessary.
To test:
Use this PR here: https://github.com/wordpress-mobile/WordPress-Android/pull/10389
- [ x ] If there are user facing changes, I have added an item to …
> Update Aztec version on Android

- RELEASE-NOTES.txt
- src/initial-html.js
This PR extract caption from image block to be shared with video block. This ports over both rich text styling and a keyboard-dismissal bug fix to the video block. It also adds the ability to select the video block when the video block's caption is selected without playing the video.
Further details and testing instructions are in the [related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16825).
There are user facing changes, so I have added an item to `RELEASE-NOTES.txt`.
> Extract caption component

- RELEASE-NOTES.txt
Fixes #1177 by hiding a block that would be replaced when the add block bottom sheet is presented.
Further description and testing steps are available in the [related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16931).
> Hide block if being replaced

- src/initial-html.js
https://github.com/WordPress/gutenberg/pull/16794 changed the way alignment is serialized from an inline style to a class name, which caused validation errors on the demo content.
To test:
- Launch the demo app and verify there are no validation errors.
> Fix initial html after changes to text alignment

- babel.config.js
- bin/ci-checks-js.sh
- jest.config.js
- libdefs.js
- package.json
- rn-cli-inside-gb.config.js
- sass-transformer-inside-gb.js
- src/_colors.scss
- src/index.js
- src/index.test.js
- src/jsdom-patches.js
- yarn.lock
Fixes #816 by adding a prettier check to our CI builds and as a pre-commit hook.
This was tested by verifying that the "Check Correctness" check on CI [failed](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/10121?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) before updating the code in this repo to comply with prettier, and the commit adding those changes caused the check to then [succeed](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/10124?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
It may be easier to review this PR by looking at the commits so you can see the changes that are not solely prettier formatting updates separately. The vast majority of the changes in this PR are just …
> Enforce Prettier (add CI and pre-commit hook)

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
Simple PR that updates Aztec iOS to v1.8.1
This is the latest version that will be used on WPiOS 13.2.
There are no behavioral changes on this new Aztec version.
To test:
- `yarn preios`
- Build and Run
- Check that it runs correctly
> Update Aztec iOS to v1.8.1

- .circleci/config.yml
This PR fixes a warning caused by RNDarkMode event emitter:
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/17186
```
axListenersExceededWarning: Possible EventEmitter memory leak detected. 11 currentModeChanged listeners added. Use emitter.setMaxListeners() to increase limit
```
To test:
- Run the demo app.
- Check that the warning does not appear.
> Fix MaxListenersExceededWarning caused by dark-mode event emitter

- __device-tests__/gutenberg-editor-paste.test.js
- src/initial-html.js
Implements https://github.com/wordpress-mobile/gutenberg-mobile/issues/689
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/16305
> Add support for the MediaText block

- .gitmodules
This PR unifies web and mobile props for MediaUpload and MediaPlaceholder components. It is the first iteration where we do not support multiple select images/videos.
Related gutenberg PR - https://github.com/WordPress/gutenberg/pull/17145
See wordpress-mobile/gutenberg-mobile#1298 and wordpress-mobile/gutenberg-mobile#1299
> MediaUpload and MediaPlaceholder unify props

- RELEASE-NOTES.txt
Fixes an issue where tapping on the empty area at the end of a post to add a new block would add the block after the currently selected block instead of at the end of the post.
Additional info and test steps in the [related gutenberg PR](https://github.com/WordPress/gutenberg/pull/16934)
> Cleanup block list

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1354
[WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12467)
**Root Cause Analysis**
I used Time Profiler to see what's taking so long and it turns out the enumeration on attributes was taking so long. So I put beginEditing/endEditing calls to make the updates as a batch.
This is still not perfect because it is a very long text but I observed that on a iPhone 6 simulator the opening of the page dropped from ~55secs to ~5secs.
**About Text Getting Invisible**
Also, you might observe that text appears as invisible. This is a [known iOS behavior](https://stackoverflow.com/questions/43703095/uitextview-is-not-showing-long-text) about rendering very long text inside a non-scrolling UITextView. If you split the …
> [iOS]Fix: Oddly formatted text hangs Gutenberg

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1368 
This PR makes sure that no selection changes are propagated after the aztec text view is no longer the first responder. 
This way when the Link Modal interface is called and the URL input is activated (becomes the first responder) the selection change on the original Aztec content is not propagated to the link UI.
To test:
- Open the demo app
- Add or edit a text block, for example paragraph
- Write some text
- Select some of the text
- Tap on the link button on the toolbar
- Make sure the link text is pre-filled with the selected text
> Only report selection changes if text view is still first responder.

- package.json
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Hotfix for the link selection bug on iOS13.
This PR was initially used to create a tag for hotfix version 1.11.1 and then it was altered to be merged to master to create version 1.13.1
To test:
- Check if links in content are tappable without opening a Safari instance.
> Work around for link selection.

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1311
This PR changes the code in the RNAztecView in order to override the `pasteWithoutFormatting` the same way we do with `paste` and do the paste action in GB instead of relying in the Aztec paste.
To test: Follow the instructions on the ticket #1311.
> Intercept paste without formatting command.

- .gitmodules
Gutenberg PR https://github.com/WordPress/gutenberg/pull/17392
This small PR moves `MediaUploadProgress` out of `image` (native) to its own component folder. In favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1313 to be able to reuse this for the Media & Text block.
To test it:
- Add an image block and check it works as expected: upload bar, placeholder.
- Add a video block and check it works as expected: upload bar, placeholder.
> Move MediaUploadPorgress to its own component folder

- .gitmodules
Fixes #1365
Please also refer to:
Merge it first gutenberg-mobile PR [Feat: Cross platform InspectorControls](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1341) and [Feat: cover cross platform RangeControl](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342)
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/17569)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1365)
It presents:
New layer on top of `BottomSheet.Cells` to use controls placed in BottomSheet in the same way as in web version.
> Refactor: BottomSheet controls

- RELEASE-NOTES.txt
Resolves part of wordpress-mobile/gutenberg-mobile#1337
This PR add an extra setting to Image Settings bottom sheet to be able to open links on a new tab (Link target).
**More info:** 
Gutenberg side PR: https://github.com/WordPress/gutenberg/pull/17675
- Build and run the mobile example app.
- On an image block, set a link and turn "Open in a new tab" ON.
- Close the bottom sheet and open the settings again.
- Check that the settings were saved and display as before.
- Press `Clear All Settings`.
- Check that all settings are removed.
> Link target option on Image Block

- .gitmodules
Fixes #1315 
Please also refer to:
Merge it first gutenberg-mobile PR [Add FloatingToolbar component](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1362)
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/17496)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1315)
It presents:
`Icon` on `Floating Toolbar` component witch allow to select parent of selected block. It is visible only when some of the `Inner Block` is selected
> Feat: Navigation Upward in InnerBlocks

- RELEASE-NOTES.txt
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1391 by the changes on https://github.com/WordPress/gutenberg/pull/17802
This PR also fixes another DarkMode issue I found while testing this:
- Typing attributes won't update appropriately when textColor changes.
To test:
- Checkout `gutenberg-mobile` PR: TBD
- Run the project on iOS 13 with dark mode.
- Add a List block.
- Check that the placeholder is properly lied out.
--
- Switch to light mode.
- Create a new List block.
- Write some text on it.
- Switch to dark mode.
- Delete the text and write new text.
- Check that the text color is white.
> iOS dark mode improvements

- Gutenberg.podspec
- ios/gutenberg.xcodeproj/project.pbxproj
- react-native-aztec/ios/RNTAztecView.xcodeproj/project.pbxproj
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.xcodeproj/project.pbxproj
This PR just updates the GB projects to have a minimum requirements of iOS 11 and to use Swift 5.
To test:
- Check if project builds
- Smoke test the demo app to see if all is correct.
> Update to iOS11 and Swift 5.

- RNTAztecView.podspec
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/pull/1426#issuecomment-540648766
To test:
- Update WPiOS Gutenberg commit hash to the latest on this PR
- Build and check that all pods builds properly.
**Note:** There might still be build errors due to https://github.com/wordpress-mobile/WordPress-iOS/pull/12581 not yet being merged.
> Update RNTAztec to iOS11

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Fixes #1403
WordPress-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10576
To test:
Follow steps listed here: https://github.com/WordPress/gutenberg/pull/17537#issue-320518695
and make sure videos and images can be selected from the picker after choosing "Choose from device".
> Filter for images and video in add media picker

- sass-transformer.js
In https://github.com/WordPress/gutenberg/pull/17883 the base SCSS styles are moving to a separate package. This updates our SASS transformer so it knows to look for them in the new path.
This can be merged before https://github.com/WordPress/gutenberg/pull/17883 since I didn't remove the old location.
To test:
Update the gutenberg submodule to https://github.com/WordPress/gutenberg/pull/17883 and see if everything runs correctly
> Import new location for base styles

- src/initial-html.js
Fixes #1411 
To test: See https://github.com/WordPress/gutenberg/pull/17936
> Fix icons for Media & Text in dark mode

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Fixes: For some unexpected reason, the line of the code which toggles editor mode is missing in this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1410/files#diff-f2e1dfe800569dfb4ee4830f88779890R540
To test:
Toggle editor mode (Html -> Visual and Visual -> Html) should work as expected.
Hey, @hypest since you will probably wrangle release `1.15.0`, just to let you know that this PR must be included in the `1.15.0` release.
> [Android] Revert missing toggle editor mode call

- react-native-aztec/android/build.gradle
This PR is in preparation for [WPAndroid updating to Gradle 5.4.1](https://github.com/wordpress-mobile/WordPress-Android/pull/10583). This update causes a build failure when `BUILD_GUTENBERG_FROM_SOURCE` is set to `true`. 
The issue is that react-native-gutenberg-bridge can not access the WordPressUtils. In particular, the WPAndroidGlueCode class fails to compile because it cannot import org.wordpress.android.util.AppLog. Switching WordPressUtils from an implementation dependency to an api dependency in react-native-aztec makes WordPressUtils available to react-native-gutenberg-bridge.
Insure that `yarn android` successfully builds the mobile-gutenberg demo app
1. Check out WPAndroid commit [91c1af7](https://github.com/wordpress-mobile/WordPress-Android/commit/91c1af7f293234ddcbd0f0ede4c6f …
> Expose WordPressUtils for consumption by react-native-gutenberg-bridge

- .gitmodules
Fixes #1384 
Ref to gutenberg: https://github.com/WordPress/gutenberg/pull/17703
To test:
1. Add an image.
2. Press and icon <img width="30" src="https://user-images.githubusercontent.com/22746080/66471147-23979080-ea8b-11e9-9d12-61350c9ae97d.png" />
3. Check the `BlockSettings` inspector
> Introduce grouping in the block settings inspector

- package.json
- react-native-aztec/android/build.gradle
This PR does only update the Aztec version used in gb-mobile to be in par with the version used in WP-Android in this PR https://github.com/wordpress-mobile/WordPress-Android/pull/10620
Replaces this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1475
To test:
Testing steps in the parent PR.
- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.
> Hotfix for WP-Android #8828 fix - Just upgrade Aztec version

- RELEASE-NOTES.txt
This PR uses onLayout and the internal State of inserter menu to force a re-render of the component on device rotation.
gutenberg PR: https://github.com/WordPress/gutenberg/pull/18101
Fixes: wordpress-mobile/gutenberg-mobile#1491
- Run the example app (iOS and Android).
- Press (+) to show the block inserter.
- Check that the layout looks fine.
- Rotate the device.
- Check that the layout rearranges.
**Note:** There's a small jump after the rotation while the layout changes. As a hotfix is probably good enough, but I'd like to check this out later on.
> Force block inserter to re-render on device rotation

- RELEASE-NOTES.txt
- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Beside fixing the request for import to send the correct parameters in
the callback, we are also improving the interface by replacing a tupple
for a structure to make parameters more explicit.
This can also be tested on the main app using this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12773
To test:
- On the image blocks check that the different sources work correctly
- Try to copy one image from the photos app and paste inside a text block, check that an image block is added and you see an image upload simulation happening.
> Fix requestImport call to send the correct arguments.

- RELEASE-NOTES.txt
- android/app/src/main/java/com/gutenberg/MainApplication.java
- react-native-aztec/android/build.gradle
- react-native-gutenberg-bridge/android/build.gradle
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/MediaOption.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- react-native-gutenberg-bridge/index.js
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Added support for giphy and pexels images
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/720
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10628
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18026
**Note: works only on Android (@etoledom  will implement iOS part of it)**
To test:
1. Open WPAndroid application
2. Create a new post or open existing
3. Create a new image block
4. Open picker
5. Click on `Choose from Free Photo Library`
6. Confirm and see that it will be shown in the new post
7. Open picker
8. Click on `Choose from Giphy`
9. Confirm and see that it will be shown in the new post
**@iamthomasbishop I have two questions regarding UI/UX:**
1. Should we show some icons for Giphy and Pexels options in the picker?
2. Are you …
> 720-Add support for giphy and pexel images

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/12730
Gutenberg counterpart of https://github.com/wordpress-mobile/WordPress-iOS/pull/12798
Since iOS 13.0 is so low on adoption, I believe is better to keep the simpler fix, regardless of the UX issue on 13.0, avoiding possible crashes.
- Took the chance to clean up some extra white-spaces on `RCTAztecView.swift`
To test:
- Tap/select text with links.
- Check that the links are not open in a browser and the text selection works.
- Check that the app doesn't crash.
> [Aztec iOS]: `shouldInteractWithURL` will return always false to avoid crashes

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes: #1519
On this PR we are sending the backspace when the last character is being deleted and
when all the text is being deleted.
This improves our handling of list blocks when all content is deleted.
To test:
- Add a new list block
- Insert some lines
- Delete all content by selecting all the content
- Check that the placeholder content shows properly
- Write some characters
- Delete them one by one
- Check that when all are deleted the placeholder shows properly.
- Check the same behaviour on the other text blocks( paragraph, heading, blockquote)
> Send backspace event to JS in more scenarios

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1534 
Bring this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1535
to release 1.16.1
To test:
- Add a new list
- Check that when adding new items to the list the block sizes correctly
- Do the same checks with quotes and image captions
> Issue/fix layout bug in ios 13.2

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
It seems #1373 is back on iOS 13.2. The latest workaround we had was working fine up to iOS 13.1, but after an upgrade you wouldn't be able to select links anymore.
The previous workaround fixed the selection issues, but was causing random crashes https://github.com/wordpress-mobile/WordPress-iOS/issues/12730
The new approach avoids implementing the problematic `textView(_:shouldInteractWith:in:interaction:)` method, and tries to disable the system gesture recognizer that handles taps on links 🙈 
To test:
- Open a post with links
- Tapping a link should not open Safari
- Tapping a link should position the cursor in the link and allow selection like in regular text
- (Bonus) Long press on a link will bring up the link preview sheet
> Fix iOS13 link tap bug

- RELEASE-NOTES.txt
Fixes #680 
GB PR: https://github.com/WordPress/gutenberg/pull/18279
To test:
- Switch to Safari and copy a link from the url bar
- Switch to GB demo app
- Select a text block
- Select a bit of text
- Tap on the link button
- Check that the URL that you copied from Safari is added to the URL field in the link modal
- Edit an already existing link and check that the link in the clipboard does not override the one already existing.
> Update GB reference to support copy of url in clipboard.

- .vscode/launch.json
It seems the old config was broken with newer versions of the extension. I removed the config and inserted the default entries.
I've also removed the options to launch iOS and Android since they are not working right now
To test:
- Open VSCode
- Run `yarn start`
- Launch the demo app on the simulator
- From VSCode, choose Debug > Start Debugging
- From the simulator, launch the dev menu and choose Debug JS Remotely
The bottom bar on VSCode should turn red, and you should be able to set breakpoints and use the debugger
> Update debug configuration for VSCode

- RELEASE-NOTES.txt
Fixes #632 
Addresses [the subcase in #632](https://github.com/wordpress-mobile/gutenberg-mobile/issues/632#issuecomment-513213114) where the new-block indicator wasn't shown when the block list was empty and not interacted with yet.
Also, showing the indicator when at the last block of the list.
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18289
To test:
1. Locally edit the `initial-html.js` file to have an empty block list
2. Run the demo app
3. Tap on the "+" button to insert a new block
4. Notice the "ADD BLOCK HERE" indicator right below the title block 🎉
To test 2:
1. Locally edit the `initial-html.js` file to have an empty block list
2. Run the demo app
3. Type some text in the "Start writing" prompt
4. Tap on the "+" button to insert a new block
4. Notice the "ADD …
> Show new block indicator in default appender too

- src/initial-html.js
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18284
Fixes #1531
> Remove custom paragraph options for media-text

- ios/gutenberg/GutenbergViewController.swift
- ios/gutenberg/MediaPickCoordinator.swift
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDataSource.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/720
This PR implements the iOS Bridge code needed for Stock Photos (Pexels) and https://github.com/wordpress-mobile/gutenberg-mobile/issues/1265
`WPiOS` PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12858
**Note:**
- The "Free Photo Library" is the same as used on Aztec.
- I decided to make the Free Photos Library multi-selectable, even though we haven't activated this feature on iOS yet. I can keep it single selectable if we decide that this is better.
- There are some few small changes on the bridge media picker/upload methods, so it would be good to test all options on all media related blocks. (cc @pinarol)
- I noticed that we could improve some things in the JS side, but opted to keep this PR focused on …
> [iOS] Implement client-defined media options.

- RELEASE-NOTES.txt
Fixes #479 
Includes the locally available block title in the "Unsupported block" UI for better clarity and context.
Work mostly performed by @illusaen. I'm opening a new set of PRs to land this fast while Wendy is temporarily away.
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18268
To test:
TBD
> Include the block title in unsupported blocks

- android/app/src/main/java/com/gutenberg/MainApplication.java
- react-native-gutenberg-bridge/android/build.gradle
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/GutenbergBridgeJS2Parent.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/RequestExecutor.java
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
- src/api-fetch-setup.js
Just looking to add the changes required for Android to your branch @etoledom . I realize this won't make a ton of sense without the WPAndroid changes for context (I'll get that up soon), but definitely let me know if you have any thoughts.
> Add Android native handling of api calls

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextFormatEnum.java
Undos more Android side changes introduced when we merged https://github.com/wordpress-mobile/gutenberg-mobile/pull/1442 into the v1.17 release branch. Apparently, a crash is happening without this PR:
```
E/SoLoader: couldn't find DSO to load: libreactnativejni.so
...
--------- beginning of crash
2019-11-14 11:34:24.902 5647-6174/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: create_react_context
Process: org.wordpress.android.beta, PID: 5647
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
at …
```
> Undo more changes related to PRE support

- RELEASE-NOTES.txt
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1266 . Further details available in the related [gutenberg PR](https://github.com/WordPress/gutenberg/pull/17577). Newer Gutenberg PR that targets the 1.17 release: https://github.com/WordPress/gutenberg/pull/18433
Because this includes an update to the AztecEditor-iOS version, merging this also needs to be coordinated with merging that update into WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/12929
> Add content alignment options to paragraph block

- RELEASE-NOTES.txt
Fixes: https://github.com/wordpress-mobile/WordPress-Android/issues/10491
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18539
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10805
To test:
Steps to repro - Case A
- Create a new post
- Click on the empty paragraph block
- Add a Page break block
- Click on the "bin" on the Page break block
- Page break block should be deleted as expected
Steps to repro - Case B
- Create a new post
- Add a Page break block
- Click on the "bin" on the Page break block
- This time the block is removed without a crash_
- Add a Page break block
- Click on the "bin" on the Page break block
- Page break block should be deleted as expected
> Fix crash which occurs after deleting image or page break block

- RELEASE-NOTES.txt
This enables the `Spacer` block in production
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1587
`Gutenberg` PR -> https://github.com/WordPress/gutenberg/pull/18605
To test:
`WordPress iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/12970
`WordPress Android` -> https://github.com/wordpress-mobile/WordPress-Android/pull/10817
> Enable Spacer block in production

- RELEASE-NOTES.txt
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1522
This PR updates the gutenberg ref to test https://github.com/WordPress/gutenberg/pull/18782
`gutenberg` side PR: https://github.com/WordPress/gutenberg/pull/18782
To test:
- Load the example content.
- Find the Image block with image.
- Press the image settings button.
- Rotate the device.
- Dismiss the settings sheet by pressing outside of it.
- Check that it does not crash. 
> Fix crash dismissing bottom-sheet on iOS after device rotation

- src/_native.ios.scss
Fixes #368 
This PR improves the style of the code block by:
- Change the font to Menlo size 14pt
- Add paddings has indicated in the ticket
- Adds a border like in the web block
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18785
To test:
- Open the demo app
- Create a new code block
- Edit the block and see if all looks good
> Improve code block style

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
This change make sure that if the textColor prop is set explicitly we also update the defaultTextColor is used in TextView
To test:
- Try to change the prop style on RichText uses to something like: `style={ { color: 'red' }}`
- See if the color is applied.
> Make sure if the textColor is changed the default text color is updated.

- package.json
Fixes #1556
To test:
0. Place a `debugger;` statement at https://github.com/wordpress-mobile/gutenberg-mobile/blob/6b11d521a51459ac342faf06a704ed4c40124cb2/src/index.js#L55
1. Run `yarn test:debug` on the CLI
2. Open Chrome, and visit: `chrome://inspect` and hit "Inspect" on the `jest file:///` target
3. The debugger will stop at a `const importLocal = require('import-local');` line, which is normal
4. Press "Play" to let the debugger continue
5. Allow some time and the debugger should stop at the `debugger` statement placed in step 0 🎉 
> Correct path to the jest binary for test debugger

- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
Related Aztec PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1247
To test:
- Check that e2e iOS tests on Device are ✅ 
- Test dark-mode colours on iOS are correct
> Update Aztec to fix CI error with xcode 10

- RELEASE-NOTES.txt
Adding release notes for [Gallery block](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1498)
To test: Check the release notes
> Add release notes for Gallery

- README.md
Make the git commands a little easier to copy by taking out `$` from the start of the lines.
This also matches with the other commands on the page which do not start with `$`.
To test: review README.md.
> Update Getting Started documentation to shorten git commands

- .github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to match the main WP apps:
1. More clear language, indicating that the author _needs_ to check the checkboxes
2. Nudge for adding tests
Taken from https://github.com/wordpress-mobile/WordPress-Android/blob/db0bba0e3012be0a0533737ac054d74453e05a34/.github/PULL_REQUEST_TEMPLATE.md
> Nudge for adding tests, clearer language on the PR template

- sass-transformer-inside-gb.js
- sass-transformer.js
Add support for [SASS partials](https://sass-lang.com/guide), as is already present [upstream](https://github.com/kristerkari/react-native-sass-transformer/blob/52884dd59582856fa17e2b2e8ca9efc37d412387/index.js#L41-L42).
This should fix the issue introduced by https://github.com/WordPress/gutenberg/pull/19159, and discussed there.
/cc @hypest 
To test:
> Sass Transformer: Also look for partials

- package.json
- yarn.lock
Fixes #1703, #1705 
On Android, some of the npm libraries we're forking are using the Maven mirror of React Native both when building them as standalone libs (on JitPack) and when built locally as normal npm deps. That wouldn't be a problem per se but, the RN version referenced in the local builds is the "latest' ([see this for example](https://github.com/wordpress-mobile/react-native-svg/blob/f155fbdd309f5e28bdbb326b819c5bf5af6f4cc9/android/build.gradle#L49)) so, when a newer version becomes available in the maven mirror it gets picked up.
We recently made available in the maven mirror some RN versions that are unfortunately incompatible with the versions expected by the forks, leading to crashes.
The versions used in local builds need to come from the local node_modules folder, and this …
> Libs forks need to use node_modules when building locally

- package.json
- yarn.lock
Follow up PR to #1706, to point to the merged PRs of the forked libraries.
To test:
1. Demo app should work as normal, including showing icons and videos
2. Pointing WPAndroid's gutenberg-mobile submodule to this PR should also work for all build modes and variants
> Use merged fork commits after the 1706 work

- symlinked-packages/@wordpress/keyboard-shortcuts
Fixes: Brings back gb master to normal
To test: 
Follow instructions on gb PR: https://github.com/WordPress/gutenberg/pull/19323
> Brings back gb master to normal

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-aztec/src/AztecView.js
Fixes #
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/19240
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1696
In this PR I created a local variable for focus state instead of using `TextInputState`, thanks to that we do not call `focus()` in `onFocus` which was a bit weird. I also pass the latest native value to `onBlur` event to update JS value if that is not correct.
> [FIX] Rich Text loop when autocompleting text on iOS

- package.json
This PR insures that `DependencyGraph.js` is not left in the root directory after running `yarn bundle`
Running `yarn bundle` patches metro to not watch files while bundling ([original PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/873)). It does this by copying a patched `DependencyGraph.js` file into the node_modules folder before bundling that disables watching. Then after bundling is finished it copies the original `DependencyGraph.js` file back into `node_modules`, but it (currently) leaves that file at the root of the directory. 
This PR uses `mv` instead of `cp` when restoring that `DependencyGraph.js` back to the `node_modules` folder. As a result, after running `yarn bundle` there is no longer a leftover `DependencyGraph.js` file in the root directory.
1. Run `yarn …
> Move DependencyGraph.js so the original file is not left over after `yarn bundle`

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.java
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1753
Root cause analysis can be found [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1753#issuecomment-571550043).
To test:
Tested with the steps:
Set locale to Turkish
Set locale to English
> Fix - Media Text: media acts like video even if I upload jpg

- package.json
- react-native-aztec/android/build.gradle
This PR points to changes in Aztec. These changes don't touch any existing interfaces and only add new functionality so they shouldn't break anything.
Aztec changes - https://github.com/wordpress-mobile/AztecEditor-Android/pull/887/commits/807062ab67edb46a777883aedc107fc80bb13659
We only want to merge this once the Aztec version is released. 
Did I update the GB version correctly @hypest ?
**Related PRs**
- Add content watcher for all the changes to AztecText - https://github.com/wordpress-mobile/AztecEditor-Android/pull/887
- WPAndroid PR - https://github.com/wordpress-mobile/WordPress-Android/pull/11065
**Test Plan** 
- There is nothing to tests since this is only a new interface not used anywhere in the code yet
> Release v1.19.1

- package.json
- yarn.lock
This reverts commit 4085aebab5483002e4512e199cf18c95f9cf022a.
Fixes #1761 
It's not clear yet why the issue is happening but, reverting in order to patch and unblock the v1.20 editor release.
Edit: With 39f9f34aab75ba11945bd465cb4bcd81cb06fa8d, I'm pointing to a react-native-video version ([here's the branch](https://github.com/wordpress-mobile/react-native-video/commits/try/fix-video-overflow-issue-in-gb-mobile-take-3)) that builds using a specific RN version (same as gutenberg-mobile at the moment of writing) and only fetching it from our remote RN maven mirror on Bintray.
To test:
1. On an Android 7 or 8 (possibly 9 too) device, run WPAndroid against this PR
2. Have a post with a vertical video in a vide block. Example content:
```
<p>hello world!</p>
<figure …
```
> Force the react-native-video fork to build against same RN version as gutenberg-mobile from maven repo

- __device-tests__/pages/editor-page.js
- src/jsdom-patches.js
https://github.com/WordPress/gutenberg/pull/18132 introduced a new way of doing accessibility labels, and relies on `DOMParser`, which doesn't exist in our jsdom implementation.
This PR adds a simple `DOMParser` implementation based on the API of our `jsdom` version.
To test:
- The app should run without crashing
- CI tests should pass
> Update Gutenberg to master

- RELEASE-NOTES.txt
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecTextShadowNode.java
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactTextInputShadowNodeFork.java
- react-native-aztec/android/src/main/res/values/template-dimens.xml
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- src/_native.android.scss
- src/_native.ios.scss
Fixes #992: Remove extra padding on text blocks.
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/18759)
⚠️ In testing this we need make sure and run `yarn start:reset`. Otherwise the metro bundler will not reflect the css changes in this PR.
> Remove extra padding on text blocks in Android 

- symlinked-packages/@wordpress/warning
Fixes an issue with missing symlink to `@wordpress/warning` package which is currently used in native file after [replacing](https://github.com/WordPress/gutenberg/commit/a3a2f7b007d349582e877e2524e0dee971fc051c) `console.warn` within `gutenberg`
To test:
* CI should be green ✅ 
* CI should be green [there](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1769) as well ✅ 
> Add @wordpress/warning package symlink

- react-native-aztec/android/build.gradle
- react-native-gutenberg-bridge/android/build.gradle
Before this fix, building the Android `react-native-gutenberg-bridge` or `react-native-aztec` modules directly (i.e., where they are the `rootProject`) would use an older version of react native. With [a recent change to the project](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1560/files#diff-50887f88a59f4879f48ea11a48b84e14) this resulted in a build error. Jitpack builds those modules directly, so builds on Jitpack were failing.
This is a temporary fix to get the Jitpack builds back to green while I work on a solution that doesn't use hardcoded values. I expect to open a new PR with a cleaner solution later today.
I'm not updating the value in the relevant package.json files in this temporary-fix-PR because it seems that we need version `v0.60.0-patched` in the package.json …
> Hardcode Android RN version in bridge and aztec

- ios/gutenberg.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/ios/RNTAztecView.xcodeproj/project.pbxproj
- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
This PR updates Aztec version to 1.15.0
WP-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13228
Fixes #
To test:
- Smoke test the demo app to see if all is good
- Do an extra check on the header block and blockquote block because of changes made in Aztec to that code.
> Update aztec to 1.15.0

- package.json
Fixes #1792 
`gutenberg`: https://github.com/WordPress/gutenberg/pull/19774
`WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11120
`WordPress-iOS`: https://github.com/wordpress-mobile/WordPress-iOS/pull/13252
This PR disables the gallery image size options on mobile. We can re-enable them after we've verified / implemented the desired behavior for mobile.
**To test:**
Steps:
* Create a gallery block with some images
* Tap the gallery
* Tap the gallery settings icon (the gear)
**Expected result:**
The image size option should not be visible in the menu.
> Hotfix v1.20.1 -> Master

- ios/gutenberg.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
xcworkspace dir makes UITests to fail.
To test:
- All tests should pass.
> [iOS] Remove xcworkspace.

- README.md
Update the example unit test link to something not broken.
I picked `develop/src/index.test.js` after finding it in a quick search, but let me know if there's a better one to link to!
To test: review README.md.
> Fix broken link in Getting Started documentation

- __device-tests__/gutenberg-editor-paragraph.test.js
- __device-tests__/helpers/utils.js
- __device-tests__/pages/editor-page.js
Partially addresses #1662 
This PR addresses _some_ of the Android e2e flakiness. In particular, it should resolve the issue where only a part of the desired text would be input on the device, resulting in an expectation failure where the actual text was only the beginning of the expected text. 
In short, this PR avoids using ADB to insert text when possible because that was found to not work consistently. For reasons discussed below, we still needed to use ADB to insert text when we wanted to append text, but there are only a few cases where that is necessary (list blocks), and the text being appended there is very short. If that ends up being a problem, we could always just disable the list tests on Android until a better solution is found.
This PR does not address the "requested …
> Android e2e test flakiness fix

- ios/Podfile.lock
- ios/gutenberg.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Fixes app crash on opening settings within `Spacer`, because of missing `RNCSlider` after updating RN.
During the building process you could notice a warning:
```
[!] use_native_modules! skipped the react-native dependency '@react-native-community/slider'. No podspec file was found.
```
I assume that autolinking requires `podspec` file to be on the project root, but in react-native-slider is nested so I had to [move up](https://github.com/wordpress-mobile/react-native-slider/commit/5ad284d92b8d886e366445bf215be741ed53ddc6).
To test:
1. remove old `node_modules`
2. `yarn clean:install`
3. `yarn ios`
4. add a `Spacer` block
5. open settings
6. app mustn't crash!
> Update ref to react-native-slider fork to support autolinking

- react-native-gutenberg-bridge/index.js
Remove the `__DEV__` flag so the Media Editor button will be available for iOS in production too.
> Remove DEV flag from Media Editor button

- .gitmodules
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/19961
* Check that the Media Edit icon matches the style of the Gallery icons
* Check that the icon only appears when the Image block is selected
> [Media Edit Icon] Show the media edit icon only if the block is selected

- RELEASE-NOTES.txt
- react-native-aztec/android/build.gradle
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
Fixes #1865 
Experimental fix by dispatching a `ReactAztecSelectionChangeEvent` when text is changed in (Android) Aztec's manager.
This fix needs some extensive testing since the extra selection changed event could have side effects in other features.
Thing is, selection changed events should be sent out anyway [by this code](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java#L138) but it looks like the listener is suspended because of [this code on the Aztec side](https://github.com/wordpress-mobile/AztecEditor-Android/blob/d2baefd3512e3c2e19a6b5a183befb4c8f108949/aztec/src/main/kotlin/org/wordpress/aztec/watchers/ZeroIndexContentWatcher.kt#L30-L32).
@khaykov , I know it's …
> Send selection change event when typing

- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java
Fixes #1870 
My current theory is that the new View is not yet in the proper position in the layout and requesting focus to it causes a scroll to the top of the ScrollView, since the coordinates of the view are not yet updated in respect to its parent. I can be wrong, haven't fully reached the bottom of this issue.
1. Open the demo app and add an image block at the top (to make the effect more noticeable)
2. Start adding paragraph block. Add more than a few so the view will need to scroll to show the whole content
3. Type "Enter" on the last paragraph block to create a new one
4. There shouldn't be a "whole list" jump to the top and back down again
There's a prior known issue with scrolling to new block added doesn't work so, this PR is not introducing that bug: …
> Schedule to request focus instead of asking immediately

- RELEASE-NOTES.txt
Fixes missing releasing notes after adding these two functionalities:
1. New block Button -> https://github.com/WordPress/gutenberg/pull/20093
2. Add scroll support inside block picker and block settings -> https://github.com/WordPress/gutenberg/pull/18574
To test:
> Update release notes

- RELEASE-NOTES.txt
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1329
We recently finished resolving behavioral issues related to updating images sizes on mobile, and are therefore removing the DEV flag blocking the feature in non-development builds.
See - wordpress-mobile/gutenberg-mobile#1593
- Gutenberg: https://github.com/WordPress/gutenberg/pull/20229
- WPiOS (for testing only) - https://github.com/wordpress-mobile/WordPress-iOS/pull/13462
- WPAndroid (for testing only) - https://github.com/wordpress-mobile/WordPress-Android/pull/11305
(Changes tested in individual PRs from https://github.com/wordpress-mobile/gutenberg-mobile/issues/1593):
(Must be tested in WP Apps, see test PRs above)
1. Add an Image Block and upload an image
2. Click the gear for block settings
3. Tap Image Size …
> Removing DEV flag for Image block size options

- .eslintignore
- .gitmodules
- jest.config.js
- jitpack.yml
- react-native-gutenberg-bridge/android/build.gradle
- rn-cli.config.js
`react-native-aztec` was moved into this repo a while ago and it's submodule was removed: https://github.com/wordpress-mobile/gutenberg-mobile/pull/465 
But this submodule was re-introduced again because of JitPack problems: https://github.com/wordpress-mobile/gutenberg-mobile/pull/486
Seems like JitPack is not an issue anymore as the CI is green in this PR so we can remove this submodule now.
> Remove react-native-aztec-old-submodule

- RELEASE-NOTES.txt
Remove duplicate release note for enabling changing images in gallery blocks from 1.22.0 as discussed in [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1924#discussion_r380403874).
> Remove duplicate gallery image size release note

- .circleci/config.yml
I realized that we don't need the CI `Yarn preios` step anymore since the `preios` is run in the build step. Recently I updated the `test:e2e:build-app:ios` script to use `yarn ios` under the hood sot the `preios` is also run.
To test:
- Green CI (it affects only CI)
> [CI] remove Yarn preios step

- RELEASE-NOTES.txt
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
Fixes #1829 
On Android when we are editing a paragraph block in landscape mode and you press the done button, an "Enter" keypress is registered. Therfore, the block is split at the point of the cursor. @iamthomasbishop indicated that the "Done" button should just close the keyboard, but that he would prefer not have the "full screen" editing type view when in landscape mode. Conveniently enough, the preferred solution is actually easier to implement. 😄 I would like to get @iamthomasbishop 's sign-off on this first though to make sure he's ok with how the view is mostly taken up by the keyboard.
I'm glad you asked! 
Before | After
--- | ---
1. Open post with paragraph block
2. Select paragraph block so that keyboard displays
3. Switch the phone to landscape mode
4. Observe that the phone …
> Avoid fullscreen text entry UI in landscape mode

- .gitmodules
- RELEASE-NOTES.txt
Fixes #1673
To test: See Gutenberg PR -> https://github.com/WordPress/gutenberg/pull/20419
> Fix Quote border-left not visible in Dark Mode

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
This PR fixes an issue where an unwanted character was inserted after dictation.
And also, now dictations on the middle of the string will be positioned correctly (not always at the end).
To test:
- Tap on the Post Title.
- Start dictating with voice.
- When finished, press Enter.
- Check that there is no [UNDEFINED] appended to the post title.
- Check for regressions on #606
> [iOS] Fix [Obj] character after dictation

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1967  
Please also refer to:
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/20572)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1967)
It presents:
Hides the ⤴️ button on the FloatingToolbar for top-level blocks when selected.
> Feat: hide hide "⤴️" button on floating toolbar

- README.md
Just a few minor fixes to the README as I get set up for the the Gutenberg testing spike!
> README: General cleanup for clarity and typos

- RELEASE-NOTES.txt
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
This reverts #1842 because not extracting the editing ui in landscape mode left too small of a window in WPAndroid on account of the top toolbar. See [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1842#issuecomment-596628153) for more details.
To test:
1. Open post with paragraph block
2. Switch the phone to landscape mode
3. Select a paragraph block so the keyboard displays
4. Observe that the extracted editing UI is presented (i.e. there is a "Done" button and you can no longer see your post.  You can only see the keyboard and a view with the text from the paragraph block.
Before Revert | After Revert
--- | ---
> Revert back to using extracted editing UI in landscape mode on Android

- .circleci/config.yml
- package.json
- yarn.lock
Update project to use react-native-url-polyfill package for the URL class.
This is related to this Gutenberg PR that adds full test for the isURL method: https://github.com/WordPress/gutenberg/pull/20537
To test:
- Make sure the unit tests run correctly
- Add a video block and insert a video
- Check if all works correctly ( the video block code uses the isURL method)
@etoledom can you check that the build process error that you saw before no longer occurs?
> Update project to use react-native-url-polyfill package for the URL class

- RELEASE-NOTES.txt
Updating gutenberg ref to fix https://github.com/wordpress-mobile/gutenberg-mobile/issues/1950
More info on the `gutenberg` side PR: https://github.com/WordPress/gutenberg/pull/20499
To test:
- Follow steps on [`gutenberg` side PR](https://github.com/WordPress/gutenberg/pull/20499).
> Fix crash pasting HTML with wrapped images.

- RELEASE-NOTES.txt
Fixes #1697 
Improves the "Take a Video" option in the choose media bottom sheet by using a different icon than the "camera" one used so far
See screenshot and testing instructions at the Gutenberg PR: https://github.com/WordPress/gutenberg/pull/20927
> Update Gutenberg ref to use video-alt2 icon

- RELEASE-NOTES.txt
Addresses #1164
To test: See https://github.com/WordPress/gutenberg/pull/20848
> Dismiss bottom sheet on return key submit

- RELEASE-NOTES.txt
GB PR: https://github.com/WordPress/gutenberg/pull/21268
To test:
- Start the demo in Android
- Check that on heading block the align toolbar is not visible/available.
> Disable align controls for the Heading block in Android

- __device-tests__/gutenberg-editor-latest-posts.test.js
- __device-tests__/pages/editor-page.js
- src/initial-html.js
- src/test/api-fetch-setup.test.js
Adds a device test for latest posts and adds the block to the initial html in order to help catch regressions
To test:
The CI run of the device tests should be enough to validate
> Add tests for Latest-Posts Bock

- bin/po2android.js
Add a new androidReplacements function to comply with Android Typography lint rules
> Add a new androidReplacements function to comply with Android Typography lint rules

- .github/PULL_REQUEST_TEMPLATE/release_pull_request.md
This PR will add a new template for release PRs to make it easier to check all the steps needed and to standardize the release PRs.
This template can then be used by using this link `https://github.com/wordpress-mobile/gutenberg-mobile/compare/master...release/1.25.0?expand=1&template=release_pull_request.md`
Or just use the normal pull request flow in github and then add this to url of the pull request preview page: `?expand=1&template=release_pull_request.md`
Fixes #
To test:
> New template for release PRs

- __device-tests__/gutenberg-editor-latest-posts.test.js
- __device-tests__/pages/editor-page.js
Fixes #
iOS was showing inconsistencies in being able to tap on Block Buttons. Previously the tests were using the `click` command which would send a command to the driver to handle the scroll and the tap. To get the tests to tap consistently the tap needed to be adjusted a few pixels inside the button. 
This also resulted in needed to reimplement the scroll for iOS. (Using a consistent version for iOS and Android wasn't working) 
Run device tests
> Fixes Latests Posts Tests by expanding the scroll to button functionality

- RELEASE-NOTES.txt
That PR is adding a missing note about adding Buttons block after merging that feature.
To test:
> Update RELEASE-NOTES after merging Buttons

- RELEASE-NOTES.txt
Remove extra line in `RELEASE-NOTES.txt` after merge FloatingToolbar PR
> Fix: remove extra line in release note fo FloatingToolbar

- package.json
- yarn.lock
Fixes https://github.com/WordPress/gutenberg/issues/19860
react-native-video PR: https://github.com/wordpress-mobile/react-native-video/pull/6
To test:
- Add a Video block check if behaviour stays the same
- Same for Media & Text block with a video
- Same for Cover block with a video
> Update react-native-video dependency to remove Apache 2.0 dependencies

- RELEASE-NOTES.txt
Revert the video player refactor to allow playing iOS videos inline.
Related GB PR: https://github.com/WordPress/gutenberg/pull/21770
To test:
- Make sure the title is completely visible on the visual mode and HTML mode.
> Update GB reference.

- react-native-aztec/android/build.gradle
Aztec Android was updated [here](https://github.com/wordpress-mobile/AztecEditor-Android/pull/900) for new AztecToolbar customization options.
This PR is for updating Gutenberg-mobile to be on the latest Aztec Android and in sync with the WordPress Android app Aztec version. 
See WordPress Android update of Aztec Version to v1.3.40 here: https://github.com/wordpress-mobile/WordPress-Android/pull/11594
You can use the following branch to test this Aztec update in WPAndroid: [woo/aztec-design-changes-TEST-gb-update](https://github.com/wordpress-mobile/WordPress-Android/tree/woo/aztec-design-changes-TEST-gb-update).
1. [x] Test blocks that use Aztec/RichText Component (Paragraph, List, Verse, etc)
2. [x] Test scrolling up and down on longer articles. 
3. [x] Test within WordPress Android …
> Updating Aztec Android ref to Release v1.3.40

- .gitmodules
Fixes #2182 
WPAndroid side PR: TBD
Our current theory is that the submodules are large enough and JitPack is not cloning then shallowly so, this PR marks the submodules as shallow by default in an attempt to minimize the size of their casual cloning.
The typical way we pull the submodules is by issuing `git submodule update --init --recursive`. The same command can still be used and it will pull a shallow copy of the submodules.
If you need to pull the whole history instead, the initial pull after a fresh clone can be: `git submodule update --no-recommend-shallow --init --recursive`
0. Prepare for a fresh clone of the repo by going into a folder that doesn't have the repo clone yet
1. Issue `git clone --single-branch --branch try/shallow-submodules …
> Turn the git submodules to shallow by default

- RELEASE-NOTES.txt
- react-native-aztec/android/build.gradle
- react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java
Enables alignment on Android for non `<p>`-based blocks. In particular,
1. Enables alignment for Heading blocks on Android (was already working on iOS);
2. Applies center alignment for the Pullquote block on Android (was already working on iOS) https://github.com/wordpress-mobile/gutenberg-mobile/issues/1854; and
3. Enables alignment for the Verse block (the option was there before, but it didn't work) https://github.com/wordpress-mobile/gutenberg-mobile/issues/2037;
4. Enables alignment for the quote block on both platforms (alignment button was present, and it would update the HTML, but visually the block did not display the selected alignment) https://github.com/wordpress-mobile/gutenberg-mobile/issues/2161
⚠️ Once the [AztecEditor-Android …
> Update Aztec-Android for alignment handling

- ios/Podfile.lock
- package.json
This PR bumps the version number in `package.json` to `1.27.0`. This should have happened with the PR merging from `master` back to `develop`, (https://github.com/wordpress-mobile/gutenberg-mobile/pull/2202), but the merge conflict was resolved incorrectly in [this commit](https://github.com/wordpress-mobile/gutenberg-mobile/commit/38e88c61070318e2804a3e10f6056fba930428e2) (necessary since we do not merge directly from `master` to `develop`, but use an intermediate branch instead).
> Bump version number in package.json to 1.27.0

- CODE_OF_CONDUCT.md
Fixes #490 
This code of conduct is a carbon copy of the one present in the Gutenberg main project.
To test:
- Just check if the file is correct.
> Add code of conduct file.

- ios/Podfile.lock
- package.json
- yarn.lock
Updates the react-native-video to version 5.0.2
Related bug: https://github.com/wordpress-mobile/WordPress-iOS/issues/13885
Related PR: https://github.com/wordpress-mobile/react-native-video/pull/8
To test:
- Smoke test the video block.
> Update react-native-video to version 5.0.2

- RELEASE-NOTES.txt
- RNTAztecView.podspec
- ios/Podfile.lock
- src/initial-html.js
Updates Aztec to version 1.19.0
To test:
- Smoke test the demo app, especially the text blocks
- Check the initial content block that has the sup and sub and see if it renders correctly.
> Issue/update aztec ios to 1.19.0

- RELEASE-NOTES.txt
Merging the 1.27.1 release back into develop [got the release notes out of order](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2246/files#diff-a3d054590c32de57d87be233927e755dR1-R4). This PR fixes that and also adds priority indicators to all the 1.28.0 release notes.
> Fix release notes

- react-native-gutenberg-bridge/android/build.gradle
Trying to improve the avoid-jitpack workflow, particularly the build speeds.
See [WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11921) for testing instructions
> Improve avoid-jitpack workflow

- react-native-gutenberg-bridge/android/build.gradle
This improves the incremental build detection following the no-jitpack changes. 
The primary motivation for this change is that the previous implementation would incorrectly find that a bundle was up-to-date if the bundle file was not present but the `upToDateIndicatorFile` was present. This could occur if there was a build failure in the `buildJSBundle` task after the `bundleUpToDateCheck` task had already created the `upToDateIndicatorFile`. It could also occur if someone deleted only the bundle file while making no other changes (see test step 9). In those scenarios, gradle would think that the bundle did not need to be rebuilt (because the `upToDateIndicatorFile` existed) even though there was no bundle file.
With these changes we no longer need the `upToDateIndicatorFile` hack. …
> Insure bundle file exists when determining up-to-date status

- react-native-gutenberg-bridge/android/build.gradle
Fixes #2302
Under circumstances that we don't quite understand yet, the gradle-node-plugin managed Node/npm/Yarn tools setup ends up in an inconsistent state and break the WPAndroid build. This PR tries to reset the state of the tools by deleting their folders (living in a temporary system directory) and let gradle-node-plugin re-setup them before building.
To test:
1. After a successful WPAndroid build, delete the `libs/gutenberg-mobile/react-native-gutenberg-bridge/android/build/assets/index.android.bundle` JS bundle and also delete the node folder `$TMPDIR/jsbundle/null/nodejs/node-v12.16.1-darwin-x64/lib/node_modules/npm`.
2. Run `./gradlew assembleVanillaDebug`. It should succeed.
3. Install the apk (or use `installVanillaDebug` in Step 2) and run the app. The block editor should …
> Delete temporary RN tools before building

- RELEASE-NOTES.txt
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/22492
In this PR i added `selectionStart` and `selectionEnd` to the `transientEdits` which results less undo levels created.
To test:
Tests from Gutenberg PR
> Add selectionStart and selectionEnd to the transientEdits

- RELEASE-NOTES.txt
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2287 https://github.com/wordpress-mobile/gutenberg-mobile/issues/2295 https://github.com/wordpress-mobile/gutenberg-mobile/issues/2267
`gutenberg`: https://github.com/WordPress/gutenberg/pull/22620
This PR fixes some strings in the mobile pages templates to be consistent, and also uses center alignment for the buttons.
In a new page, apply each of the templates and verify that the buttons are center aligned, and that the following strings are consistent "Let's build something together!" (should have an exclamation mark at the end), and "Get in Touch" (consistently title case for each instance).
> Fix page templates button alignment and strings

- __device-tests__/gutenberg-editor-lists.test.js
Also re-enables the list spaces e2e test, which should now pass with the latest gutenberg code merged in.
Before merging this we need to update the gutenberg submodule ref to the gb `master` hash after https://github.com/WordPress/gutenberg/pull/22607 is merged.
> Update to latest gutenberg

- ios/Podfile
- ios/Podfile.lock
Fixes #1218 
This update of Aztec fixes another instance of the underlines going the full width of a line.
To test:
- Create a list block
- Write some test in an item
- Add a link to the full text on the line
- Check that the underline does not expand to the full line.
- Tap Enter
- Check that the underline does not expand to the full line.
- Test the same using the Paragraph block and the Quote block
> Update Aztec to version 1.19.2

- RNTAztecView.podspec
- ios/Podfile
- ios/Podfile.lock
This PR updates the Aztec reference to a proper release of 1.19.2 instead of just the hash version
To test:
- Just check if CI is green
> Update to official version of Aztec 1.19.2

- __device-tests__/gutenberg-editor-lists-canary.test.js
We didn't have canary tests yet when I added the test for list spaces, and it's a perfect candidate to _not_ be run with every PR, so this PR addresses that. 
The diff makes it a little hard to see exactly what I have changed. I have updated the "old" `gutenberg-editor-lists.test.js` file to only have the list spaces test. I also created a new `__device-tests__/gutenberg-editor-lists-canary.test.js` that contains the other list tests that should run in the canary job.
To test:
* Verify that the list with spaces test does not run with the PR's canary jobs ([Android](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/6889/workflows/1f10faff-ac32-4386-ac23-efa0b5ab068a/jobs/36550/steps), [iOS](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile …
> Update list spaces test to not be canary test

- docs/Releasing.md
I would like to try preserving our release checklist here in the github repo. Until now, we've just been copying the release checklist from the previous release. There are three main problems with doing this, and I think creating a release checklist template on Github solves them:
1. **It takes manual editing to "clean" the previous release's checklist.** Mostly unchecking checkboxes and removing the usernames that get attached to any "completed" items. This only takes maybe 5 minutes, but it's a tedious 5 minutes that we shouldn't have to lose everytime we do a release or hotfix.
2. **Checklist updates are made by a single person editing the checklist item without any review** (unless they specifically reach out and solicit feedback). This is troubling considering how important it is to …
> Add Release Checklist

- .vscode/settings.json
Currently in VS code when you search for a specific string you get back results that include build files, and symlinked files so the string in question can appear in multiple places. 
This PR tries to fix that in the VS code editor since by removing specific folders from search.
To test:
- Pull in this PR, perform a search in VS code do you get back files as expected? 
> Update the VS code search settings to that seaching is easier

- RELEASE-NOTES.txt
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
Expands #2380 to include the Android side of the call to get content information.
To test:
Use the WPAndroid PR to test: https://github.com/wordpress-mobile/WordPress-Android/pull/12191
> Glue code to get content info metrics

- .github/PULL_REQUEST_TEMPLATE.md
- docs/Release-notes.md
This PR add a release note doc so that we can explain why and how to add a release note to the `RELEASE-NOTE.txt` file. 
Does the new doc make sense what else should we add to it? 
Anything needs to be removed? 
> Add Release notes doc

- .circleci/config.yml
Try to fix watchman install on circle-ci.
> Unlink python2 before installing watchman

- bin/release_automation.sh
This updates the release script to also update the version in package-lock.json. It also commites the version changes separately from any preios changes.
I don't love the fact that I am manually editing the `package-lock.json` file here, but that seemed better than running `npm install` and either (a) blindly committing any resulting changes or (b) aborting the script anytime there were changes to anything other than the version number. Certainly open to other thoughts/ideas though.
To test:
Smoke test the release script and make sure the resulting commits make sense.
> Update version change in package-lock.json and commit version changes separately

- RELEASE-NOTES.txt
Fixes #2364
Related GB PR: https://github.com/WordPress/gutenberg/pull/23057
To test:
1. Download WordPress-iOS. 
2. Make sure that he WordPress-iOS repo is on the same level as this directory. (gutenberg-mobile) 
> - gutenberg-mobile (this repo)
> - WordPress-iOS (https://github.com/wordpress-mobile/WordPress-iOS)
3. Run the following command on the WordPress-iOS repo
```
$ export LOCAL_GUTENBERG=1
bundle exec pod update
``` 
4. Load this PR. 
5. Build the iOS app using xcode and send it open it on your device. 
6. Navigate to the Pages screen. 
7. Enable VoiceOver using Siri. 
8. Navigate to a new post. 
Before:
See https://cloudup.com/cNlMs6Fbu_F
After: You should get this experience 
https://cloudup.com/cjd-RHZpyQM
> [Gutenberg] Add AccessibilityLabel and hint to AztecViewManager

- .github/PULL_REQUEST_TEMPLATE/release_pull_request.md
- docs/Releasing.md
Some relatively minor updates to the release docs. This is mostly just removing steps that are automatically handled by the release script. The only real addition is giving providing the text for some relatively PR descriptions in the main apps that primarily refer to the gb-mobile PR.
Definitely open to feedback on any of these changes.
To test:
Insure that the checklist is still accurate and can be copied into a draft release checklist post on a p2.
> Update release checklist with usage of release_automation.sh script

- bin/release_automation.sh
- bin/release_prechecks.sh
- docs/Releasing.md
Adds checks for milestone PRs and Aztec versions that are not release versions to the release script.
To test:
Verify that the checks work as expected.
> Add release prechecks

- .github/PULL_REQUEST_TEMPLATE/release_pull_request.md
- docs/Releasing.md
This PR:
1. Updates the release PR template to include to include a link to the related PR for each change in the release; and
2. Adds a step to the "Specific tasks after a PR has been merged after the freeze" portion of the release checklist for adding any release updates to the "Extra PRs that Landed After the Release Was Cut" section of the gb-mobile release PR.
To test:
Make sure the updates make sense.
> Tweak Release docs

- .github/PULL_REQUEST_TEMPLATE.md
This fixes two issues with the PR template:
1. The links used relative paths from the root of the repository, which seems to be causing github to look for a matching branch (and failing to find one). For example: [Release Notes doc](docs/Release-notes.md).
2. The RELEASE_NOTES link was formatted as code with backticks, which caused it to not actually show a link but instead to show the raw text: `[RELEASE_NOTES.txt](RELEASE_NOTES.txt)`.
You can see examples of the PR template before these changes in the checklist below, which is unchanged from the template, and what it should look like after these changes in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2517.
To test:
> Fix links in PR template

- bin/release_automation.sh
Updating the release script to push the gutenberg release branch. I think we should do this because we update the gutenberg branch with the version number and the updated submodule hash is committed to gb-mobile release branch, but the referenced commit won't be pushed to the gb repository unless/until it is manually pushed. Until that is done no one else would be able to build the release branch.
To test:
Verify that the release script will push the gb branch.
> Update release script to push gutenberg release branch

- bin/release_automation.sh
- bin/release_utils.sh
This adds opening the gutenberg release PR to the release automation script. In doing that, it automatically includes a link to the gb-mobile PR in the gutenberg PR description. In addition, it prints the list of opened PRs at the end of the script.
Assuming this works well, I think it should be relatively straightforward to add the WPiOS and WPAndroid PRs to this script as well. But I figured we should see how this works first.
To test:
Make sure the release script runs smoothly and opens draft PRs in gb && gb-mobile with appropriately updated branches.
> Have release script open Gutenberg PR

- package.json
Gutenberg PR https://github.com/WordPress/gutenberg/pull/24338
Fixes Failing CI e2e test. Android e2e tests started failing after removing the scroll view from the inserter menu. I couldn't reproduce it on my side but I could fix that by using swipe gesture instead of sending the keycode 20 (arrow down).
I created the same Simulator as on Sauce Labs, used the same version of Appium and tests were passing on my side. I also tried to send locally keyevent by  `adb shell input keyevent 20` and that also works. However, I used the mechanism from here https://github.com/WordPress/gutenberg/pull/24338/files#diff-34060c7868e5c5d05b0a7f37b80fd440R453 that simulates the swipe gesture and now tests pass.
To test:
- Green e2e tests locally
- Green CI tests here …
> [FIX][Android] E2E tests - swipe inserter instead of sending the keycode 20

- RELEASE-NOTES.txt
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/24116
In this PR i added selectionStart and selectionEnd to the transientEdits which results less undo levels created.
To test:
Tests from Gutenberg PR
> [RNMobile] create undo level less frequently

- jest.config.js
- third-party-podspecs/RNCMaskedView.podspec.json
- third-party-podspecs/RNGestureHandler.podspec.json
- third-party-podspecs/RNReanimated.podspec.json
- third-party-podspecs/RNScreens.podspec.json
- third-party-podspecs/react-native-safe-area-context.podspec.json
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/23782
In this PR I added a `react-navigation` to use in bottom-sheet. The `react-navigation` requires a few native modules to be linked so I had to add `podspecs` files for each of them for iOS and fork each of them and add jitpack setup for Android.
This also brings a possibility to
- use `react-native-reanimated` instead of `Animated` from `react-native`
- use `react-navigation` somewhere else in the application. (i.e on the top level and add the HTML mode as a separate screen)
To test:
- Check settings of each block
- Open Button Block settings
- Click on Text Color / Backgrounds color
- The navigation inside bottom sheet should be possible
- Play a bit with colors and check if the button reflecting these changes
- Try the …
> Bottom sheet navigation

- bin/release_automation.sh
- docs/Releasing.md
This PR:
- Fixes release script having wrong WPAndroid remote name
- Fixes PR formatting to correctly include `RELEASE-NOTES.txt` text
- Creates `gutenberg/after_x.xx.x` branch in WPiOS and WPAndroid
- Updated release checklist accordingly
To test:
1. Run the script and use an unusually high version number 
1. Check if Gutenberg, GB-Mobile, WPiOS and WPAndroid PRs are created as drafts
1. Check if PRs have correct descriptions and changes
1. Close the draft PRs
1. Check if `gutenberg/after_x.xx.x` branches are created in WPiOS and WPAndroid repos
1. Delete `gutenberg/after_x.xx.x` branches
> Improve release script
