wordpress-mobile/gutenberg-mobile

- package.json
- store/index.js
- yarn.lock
`devToolsEnhancer` allows to
* Visualization of state, state history and state diff, and
* Dispatch actions from Chrome Redux devtools.
> Add Redux Devtool Enhancer as a developer dependency to the project

- .babelrc
- .flowconfig
- jest.config.js
- package.json
- sass-transformer.js
- src/app/globals.js
- yarn.lock
This is a set of changes I had to apply to my local copy to make it work on iOS using the simulator they provide.
`yarn ios` - make sure it works
`yarn test` - make sure it still passes
Hopefully it should work also with:
`yarn android` :)
> Build: Make app work on iOS

- ios/gutenberg.xcodeproj/project.pbxproj
- ios/gutenberg.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- ios/gutenberg.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Opening the `.xcodeproj` file and closing it is currently producing the files that are added in this PR.  There are no other changes in this PR than adding those files to version control.
These files should not be ignored as they contain important shared data.
Run the app normally and make sure it works.
> Adds a few fundamental Xcode files to the repo.

- package.json
- yarn.lock
This PR solves #71.  It's not easy to reproduce the error show in #71, but I've tested this fix in a situation in which no other fix would make the error go away, and it's working consistently fine.
Just do a clean checkout of the project and run it for iOS to test.
> Solves a problem with the resolution of @babel/runtime

- .babelrc
- jest.config.js
- src/block-management/block-holder.js
- src/parser/block-parser-paragraph.test.js
- src/store/index.js
- wordpress/hooks.js
<del>This PR is branched on the top of #80 "Update to latest GB master", so don't merge this before.</del>
Pretty simple PR in this repository:
- Changed the demo app that now loads & parses valid Paragraph blocks from HTML code.
- Use an updated version of GB hash that added support for:
-- RichText component on mobile (still need to optimize it a little bit better)
-- Add a Paragraph block for mobile
Most of the work was done in a separate branch/PR in the Gutenberg repository here:
https://github.com/WordPress/gutenberg/tree/rnmobile/port-para-block-use-latest-gb-master-july
iOS: No errors, but para blocks are empty.
> Introduce paragraph block and RichText component for mobile

- android/build.gradle
- src/block-management/block-manager.js
This PR updates the version being used of the aztec-rn library.
Because of that it updates the following:
- build tools version for Android
- Update event interface for contentSizeChange
- Small improvements on display of list to avoid the keyboard.
> Update Aztec RN version

- src/app/App.test.js
- src/block-management/block-holder.js
- src/block-management/block-holder.scss
- src/block-management/block-manager.js
- src/block-management/block-manager.scss
- src/block-management/block-styles.scss
I tweaked some of the styles to make things nicer for the demo and hid the block titles by default, adding a switch for that.
> Nicer UI from the demo

- jest.config.js
- src/block-management/block-holder.js
- src/block-management/block-manager.js
This PR adds support for the toolbar specific items to change the type of Header (h2, h3, h4).
> Heading toolbar

- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/GutenbergBridgeDelegate.h
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.m
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/192
This has a child PR so that needs to be merged first:
https://github.com/WordPress/gutenberg/pull/11635
To test you can refer to steps on [parent PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10430)
> Handle media library open request in iOS-RN bridge

- docs/Releasing.md
Document the changes in #247 and #255 to generate new releases with `yarn version`
> Adding doc for making new releases

- README.md
Simply proposes fixing the three minor typos in the README file. :)
(cc @daniloercoli)
> README: Fix Minor Typos

- src/components/html-text-input.scss
Changes the HTML editor background to white.
Fixes #366. (the scoped down version of that issue)
Just launch the editor and make sure the HTML editor background is white.
> The HTML editor background is now white.

- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/ReactNativeGutenbergBridge/RNReactNativeGutenbergBridgeModule.java
Fixed: Missing react method signature annotation
> Added missing react method signature

- ios/gutenberg/GutenbergViewController.swift
- react-native-gutenberg-bridge/ios/Gutenberg.swift
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge.swift
Refs: #611 
This implements the code to set focus on the title for iOS.
> Implement set focus on title.

- package.json
This PR merges the release 1.1.0 back into develop.
This was already tested here:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/726
- https://github.com/wordpress-mobile/WordPress-Android/pull/9385
- https://github.com/wordpress-mobile/WordPress-iOS/pull/11221
> Merge release 1.1.0 back into develop

- react-native-aztec/android/build.gradle
- react-native-aztec/package.json
This updates Aztec Android to v1.3.22
> Update Aztec Android to v1.3.22

- ios/gutenberg.xcodeproj/project.pbxproj
- ios/gutenberg/AppDelegate.swift
- ios/gutenberg/MediaPickCoordinator.swift
Update the demo app to use Swift 4.2
> Update demo app to swift 4.2

- package.json
- yarn.lock
Updating version reference as detailed in https://github.com/wordpress-mobile/react-native-recyclerview-list/pull/14
> Updated recyclerview-list reference

- react-native-aztec/android/build.gradle
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
- react-native-aztec/package.json
Updating Aztec Android to v1.3.24 and Aztec iOS to 1.5.2.
> Update Aztec for v1.2.0 release

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
- react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.swift
Refs #897 
This PR addresses the issues raised on the ticket above:
- It adds more spacing between paragraph lists
- It adds space between the list bullet and the text
Here is a screenshot:
> Address list design review on iOS

- package.json
- react-native-aztec/android/build.gradle
- react-native-aztec/ios/Cartfile
- react-native-aztec/ios/Cartfile.resolved
This merges Release/1.4.0 into develop.
> Merge Release/1.4.0 into develop

- README.md
Updates the README to point to project Wiki for UI tests
> Update README to point to project Wiki for UI tests

- RELEASE-NOTES.txt
Fixes #1070 and #1113 
Details and testing instructions are included in the companion PR: [WordPress/gutenberg#16722](https://github.com/WordPress/gutenberg/pull/16722)
> Fix loss of center alignment in image captions on Android

- package.json
- react-native-gutenberg-bridge/ios/Gutenberg.swift
PR to merge hotfix 1.10.2 into master
Changes were tested and approved via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1271
cc @loremattei
> Hotfix v1.10.2 -> Master

- package.json
- react-native-aztec/android/build.gradle
PR to merge hotfix 1.10.3 into master
Changes were tested and approved via #1292
Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10389
iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12315
> Hotfix v1.10.3 -> Master

- .gitmodules
Fixes #
Implements #1319 
Gutenberg related PR : [#17251](https://github.com/WordPress/gutenberg/pull/17251)
> Add support for group component

- .gitmodules
Fixes #
To test: https://github.com/WordPress/gutenberg/pull/17325
> Remove redundant bg color within button appender

- .gitmodules
> Fix lint issue on rmobile/master on gutenberg repo

- .gitmodules
Fixes #1418 
Ref to gutenberg repo: https://github.com/WordPress/gutenberg/pull/17812
To test:
> Don't display UngroupingButton for Media&Text block

- .gitmodules
is a part of #1300
[Gutenberg related PR](https://github.com/WordPress/gutenberg/compare/rnmobile/master...callstack:rnmobile/range-control)
> Feat: cover cross platform RangeControl

- RELEASE-NOTES.txt
Fixes #198 . Further details and testing instructions are in the related [gutenberg PR](https://github.com/WordPress/gutenberg/pull/17962).
> Add image alignment controls

- react-native-aztec/ios/RNTAztecView/RCTAztecView.swift
Fixes #1534 
To test:
- Add a new list
- Check that when adding new items to the list the block sizes correctly
- Do the same checks with quotes and image captions
> Signals the need to relayout view after HTML change.

- react-native-aztec/ios/RNTAztecView/RCTAztecViewManager.m
Remove unused methods from the bridge.
The methods that back these declarations no longer exist but this declarations stay behind.
To test:
- Check if code compiles and demo app is working correctly.
> Remove declaration on bridge of unused methods.

- RELEASE-NOTES.txt
- react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/Media.java
- src/initial-html.js
Fixes #690 
Gutenberg PR -> https://github.com/WordPress/gutenberg/pull/19534
To test: See Gutenberg PR
> [RNMobile] Shortcode block support

- package.json
- symlinked-packages/@wordpress/icons
- symlinked-packages/@wordpress/primitives
- yarn.lock
Recent changes introduced the icons and primitives package and a new dependency for data.
To test:
- Test should pass
> Update to gutenberg master

- ios/gutenberg.xcodeproj/project.pbxproj
- ios/gutenberg/Info.plist
- package.json
- react-native-gutenberg-bridge/ios/RNReactNativeGutenbergBridge-Bridging-Header.h
- src/initial-html.js
This PR cleans up some iOS project definitions to make the project cleaner on iOS. It also updates the initial content HTML to avoid transformation warnings on startup.
To test:
- Make sure the app builds and runs.
- Check the demo content.
> Project cleanup

- ios/Podfile.lock
To test:
- Just check if CI builds properly
> Update podfile.lock file to latest version.

- README.md
> Readme: Add command for running a single e2e test

- src/api-fetch-setup.js
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2038
`gutenberg:` https://github.com/WordPress/gutenberg/pull/21025
Adjusts the fetching of categories from using `fetchRequest` to use `apiFetch` which also removed the need for casting the platform response and converting it to JSON for Android
https://github.com/WordPress/gutenberg/pull/20832 Introduced an issue with Query Controls in order to maintain the stable state of these controls I cloned that file to `index.native.js` and removed the mobile-specific code in the old file. There seem to be a lot of planned changes there so we can probably reassess combining them later.
Resolved the issue mentioned here https://github.com/WordPress/gutenberg/pull/20301#discussion_r392873584
Tested following the steps here: …
> Add support to Categories as part of the API fetch methods

- RELEASE-NOTES.txt
| Paragraph | Image | MediaText |
|----------|---------|------------|
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 17 16 25](https://user-images.githubusercontent.com/651601/77782334-01042e80-704f-11ea-904e-40c55dafd2e9.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 17 16 42](https://user-images.githubusercontent.com/651601/77782329-006b9800-704f-11ea-9a06-7d4c68587c41.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 17 17 21](https://user-images.githubusercontent.com/651601/77782311-fba6e400-704e-11ea-8cfb-ab8a4364ea8f.png) |
To test:
- Check the alignment toolbar of the following blocks
- Paragraph
- Image
- MediaText
> Makes alignment toolbar collapsible

- __device-tests__/gutenberg-editor-latest-posts.test.js
- __device-tests__/pages/editor-page.js
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1963
`Gutenberg PR` -> https://github.com/WordPress/gutenberg/pull/21426
To test check the Gutenberg PR description.
> Blog layout template

- RELEASE-NOTES.txt
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/22129
To test:
> Remove subscription button from blog template

- RELEASE-NOTES.txt
After change FloatingToolbar position we decide to add some entry/exit animation according to [comment with animation guideline](https://github.com/WordPress/gutenberg/pull/21446#issuecomment-615417890)
Please also refer to:
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/22146)
To test:
TBD
> Feat: entry/exit animation in FloatingToolbar

- src/initial-html.js
Clean up of the initial HTML to better show all supported blocks,
in a specific order and with the latest version of block attributes.
To test:
- Build the demo app
- Check that the initial content is ok 
> Update initial HTML.

- __device-tests__/helpers/caps.js
Update version of Appium used in Sauce Labs
To test:
- Check if full CI tests go all green.
> Update Appium version to 1.16.0

- docs/Releasing.md
To test:
- Check the releasing doc to see if all is correct.
> Update steps to reflect the mono repo organization

- docs/Releasing.md
Updating the release checklist based on the monorepo changes.
> Updating release checklist

- RELEASE-NOTES.txt
This PR adds support for the client to set a custom loading view while the editor is starting up.
Fixes #1179
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14310
To test:
- Check out WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14310
- Follow the steps described in that PR.
> [iOS] Adding support for custom loading views

- .github/PULL_REQUEST_TEMPLATE/release_pull_request.md
- docs/Releasing.md
Here are some points I noticed that could be improved while creating the [1.34.0 release](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2529).
> Update release pull request and checklist template
